// vuejs-files/template-rtl/src/views/layouts/Sidebar.vue
<template>
    <!-- Sidebar -->
			<div class="sidebar" id="sidebar">
				<div class="sidebar-inner">
				 <perfect-scrollbar class="scroll-area"  :settings="settings" @ps-scroll-y="scrollHanle">
						<div id="sidebar-menu" class="sidebar-menu">
							<ul>
								<li class="menu-title"><span>Main</span></li>
								<li v-bind:class="{'active': currentPath == 'index' || currentPath == '/'}">
									<router-link to="/index"><i data-feather="home"></i>  <span>Dashboard</span></router-link>
								</li>
								<li v-bind:class="{'active': currentPath == 'customers' ||  currentPath == 'add-customer' || currentPath == 'edit-customer'}">
									<router-link to="/customers"><i data-feather="users"></i><span>Customers</span></router-link>
								</li>
								<li v-bind:class="{'active': currentPath == 'estimates' || currentPath == 'add-estimate' || currentPath == 'view-estimate' || currentPath == 'edit-estimate'}">
									<router-link to="/estimates"><i data-feather="file-text"></i> <span>Estimates</span></router-link>
								</li>
								<li class="submenu" v-bind:class="{'active': currentPath == 'invoices-settings' || currentPath == 'view-invoice' || currentPath == 'edit-invoice' || currentPath == 'tax-settings'  || currentPath == 'add-invoice' || currentPath == 'invoice-grid' || currentPath == 'invoices' || currentPath == 'edit-invoice' || currentPath == 'add-invoice' || currentPath == 'invoices-recurring' || currentPath == 'invoices-paid' ||  currentPath == 'invoices-overdue' ||   currentPath == 'invoices-draft' ||  currentPath == 'bank-settings' || currentPath == 'invoices-cancelled'}">
									<a href="javascript:void(0)"><i data-feather="clipboard"></i> <span> Invoices</span> <span class="menu-arrow"></span></a>
									<ul>
										<li><router-link to="/invoices" v-bind:class="{'active': currentPath == 'invoices-recurring' ||  currentPath == 'invoices-paid' ||  currentPath == 'invoices-overdue' ||   currentPath == 'invoices-draft' ||  currentPath == 'invoices-cancelled'}">Invoices List</router-link></li>
										<li><router-link to="/invoice-grid">Invoices Grid</router-link></li>
										<li><router-link to="/add-invoice">Add Invoices</router-link></li>
										<li><router-link to="/edit-invoice">Edit Invoices</router-link></li>
										<li><router-link to="/view-invoice">Invoices Details</router-link></li>
										<li><router-link to="/invoices-settings" v-bind:class="{'active': currentPath == 'bank-settings' || currentPath == 'tax-settings'}">Invoices Settings</router-link></li>
									</ul>
								</li>
								<li v-bind:class="{'active': currentPath == 'add-payments' || currentPath == 'payments'}">
									<router-link to="/payments"><i data-feather="credit-card"></i> <span>Payments</span></router-link>
								</li>
								<li v-bind:class="{'active': currentPath == 'expenses' || currentPath == 'add-expenses' || currentPath == 'edit-expenses'}">
									<router-link to="/expenses"><i data-feather="package"></i> <span>Expenses</span></router-link>
								</li>
								<li class="submenu" v-bind:class="{'active': currentPath == 'taxs-report' || currentPath == 'profit-loss-report' || currentPath == 'sales-report' || currentPath == 'expenses-report'}">
								<a href="javascript:void(0)"><i data-feather="pie-chart"></i> <span> Reports</span> <span class="menu-arrow"></span></a>
								<ul>
									<li><router-link to="/sales-report">Sales Report</router-link></li>
									<li><router-link to="/expenses-report">Expenses Report</router-link></li>
									<li><router-link to="/profit-loss-report">Profit & Loss Report</router-link></li>
									<li><router-link to="/taxs-report">Taxs Report</router-link></li>
								</ul>
							</li>
								<li v-bind:class="{'active': settingsPath}">
									<router-link to="/settings"><i data-feather="settings"></i> <span>Settings</span></router-link>
								</li>
								<li class="submenu" v-bind:class="{'active': currentPath == 'inbox' || currentPath == 'calendar' || currentPath == 'chat'}">
									<a href="javascript:void(0)"><i data-feather="grid"></i> <span> Application</span> <span class="menu-arrow"></span></a>
									<ul>
										<li><router-link to="/chat">Chat</router-link></li>
										<li><router-link to="/calendar">Calendar</router-link></li>
										<li><router-link to="/inbox">Email</router-link></li>
									</ul>
								</li>
								<li class="menu-title"> 
									<span>Pages</span>
								</li>
								<li v-bind:class="{'active': currentPath == 'profile'}"> 
									<router-link to="/profile"><i data-feather="user-plus"></i> <span>Profile</span></router-link>
								</li>
								<li class="submenu">
									<a href="javascript:void(0)"><i data-feather="lock"></i> <span> Authentication </span> <span class="menu-arrow"></span></a>
									<ul>
										<li><router-link to="/login"> Login </router-link></li>
										<li><router-link to="/register"> Register </router-link></li>
										<li><router-link to="/forgot-password"> Forgot Password </router-link></li>
										<li><router-link to="/lock-screen"> Lock Screen </router-link></li>
									</ul>
								</li>
								<li class="submenu">
									<a href="javascript:void(0)"><i data-feather="alert-octagon"></i><span> Error Pages </span> <span class="menu-arrow"></span></a>
									<ul>
										<li><router-link to="/404">404 Error </router-link></li>
										<li><router-link to="/500">500 Error </router-link></li>
									</ul>
								</li>
								<li v-bind:class="{'active': currentPath == 'users'}"> 
									<router-link to="/users"><i data-feather="user"></i> <span>Users</span></router-link>
								</li>
								<li v-bind:class="{'active': currentPath == 'blank-page'}"> 
									<router-link to="/blank-page"><i data-feather="file"></i> <span>Blank Page</span></router-link>
								</li>
								
								<li class="menu-title"> 
									<span>UI Interface</span>
								</li>
								<li v-bind:class="{'active': currentPath == 'components'}"> 
									<router-link to="/components"><i data-feather="layers"></i><span>Components</span></router-link>
								</li>
								<li class="submenu" v-bind:class="{'active': currentPath == 'form-basic-inputs' || currentPath == 'form-input-groups' || currentPath == 'form-horizontal' || currentPath == 'form-vertical' || currentPath == 'form-mask' || currentPath == 'form-validation'}">
									<a href="javascript:void(0)"><i data-feather="columns"></i> <span> Forms </span> <span class="menu-arrow"></span></a>
									<ul>
										<li><router-link to="/form-basic-inputs">Basic Inputs </router-link></li>
										<li><router-link to="/form-input-groups">Input Groups </router-link></li>
										<li><router-link to="/form-horizontal">Horizontal Form </router-link></li>
										<li><router-link to="/form-vertical"> Vertical Form </router-link></li>
										<li><router-link to="/form-mask"> Form Mask </router-link></li>
										<li><router-link to="/form-validation"> Form Validation </router-link></li>
									</ul>
								</li>
								<li class="submenu" v-bind:class="{'active': currentPath == 'data-tables' || currentPath == 'tables-basic'}">
									<a href="javascript:void(0)"><i data-feather="layout"></i> <span> Tables </span> <span class="menu-arrow"></span></a>
									<ul>
										<li><router-link to="/tables-basic">Basic Tables </router-link></li>
										<li><router-link to="/data-tables">Data Table </router-link></li>
									</ul>
								</li>
							</ul>
						</div>
				</perfect-scrollbar>
				</div>
			</div>
			<!-- /Sidebar -->
</template>

<script>
    import {PerfectScrollbar}  from 'vue3-perfect-scrollbar'
    import 'vue3-perfect-scrollbar/dist/vue3-perfect-scrollbar.css'
    import feather from 'feather-icons'
    export default {
		components: {
		 PerfectScrollbar 
		},
		mounted() {

			feather.replace()
			$('#sidebar-menu a').on('click', function (e) {
			if ($(this).parent().hasClass('submenu')) {
				e.preventDefault();
			}
			if (!$(this).hasClass('subdrop')) {
				$('ul', $(this).parents('ul:first')).slideUp(350);
				$('a', $(this).parents('ul:first')).removeClass('subdrop');
				$(this).next('ul').slideDown(350);
				$(this).addClass('subdrop');
			} else if ($(this).hasClass('subdrop')) {
				$(this).removeClass('subdrop');
				$(this).next('ul').slideUp(350);
			}
		});
		 
		$('#sidebar-menu ul li.submenu a.active').parents('li:last').children('a:first').addClass('active').trigger('click');
	
		},
		computed: {
			currentPath() {
				return this.$route.name;
			},
			settingsPath() {
				return  this.$route.name == 'settings'  || this.$route.name == 'preferences' || this.$route.name == 'tax-types' || this.$route.name == 'expense-category' || this.$route.name == 'notifications' || this.$route.name == 'change-password' || this.$route.name == 'delete-account'
			}
		},
		  data() {
    return {
                settings: {
                    suppressScrollX: true,
                },
                activeClass: 'active',
            };
     

              //  isactive : true
    },
    methods: {
    scrollHanle(evt) {
      console.log(evt)
    }
  },
}
</script>
<style>
    .scroll-area {
      position: relative;
      margin: auto;
      height: calc(100vh - 60px);
      background-color: transparent !important;
  }
</style>

// reactjs-files/template/src/layouts/Sidebar.jsx
import React, { useEffect,useState} from 'react';
import { Link, withRouter } from 'react-router-dom';
import FeatherIcon from 'feather-icons-react';
import { Scrollbars } from 'react-custom-scrollbars';

const Sidebar = (props) => {

const [isSideMenu, setSideMenu] = useState("")

	const toggleSidebar = (value) => {
		console.log (value);
		setSideMenu(value)
		
	}
	
    console.log("Working", isSideMenu)

			
		let pathName = props.location.pathname;
        return(



        <div className="sidebar" id="sidebar">
					<Scrollbars      
                    autoHide
                    autoHideTimeout={1000}
                    autoHideDuration={200}
                    autoHeight
                    autoHeightMin={0}
                    autoHeightMax="95vh"
                    thumbMinSize={30}
                    universal={false}
                    hideTracksWhenNotNeeded={true}
                    >
                <div className="sidebar-inner slimscroll">
                    <div id="sidebar-menu" className="sidebar-menu">
                        <ul>
                            <li className="menu-title"><span>Main</span></li>
                            <li className={`${'/index' === pathName ? 'active' : '' }`}>
                                <Link to="/index"><FeatherIcon icon="home" /> <span>Dashboard</span></Link>
                            </li>
                            <li className={`${'/customers' === pathName || '/add-customer' === pathName ||'/add-customer' === pathName ? 'active' : '' }`}>
                                <Link to="/customers"><FeatherIcon icon="users" /><span>Customers</span></Link>
                            </li>
                            <li className={`${'/estimates' === pathName || '/add-estimate' === pathName ||'/edit-estimate' === pathName ||'/view-estimate' === pathName ? 'active' : '' }`}>
                                <Link to="/estimates"><FeatherIcon icon="file-text" /><span>Estimates</span></Link>
                            </li>
                           
                            <li className={`${'/invoices' === pathName || '/invoice-details' === pathName  || '/tax-settings' === pathName || '/invoice-paid' === pathName || '/invoice-overdue' === pathName || '/invoice-draft' === pathName || '/invoice-recurring' === pathName || '/invoice-cancelled' === pathName|| '/bank-settings' === pathName || '/invoices-settings' === pathName || '/invoice-grid' === pathName || '/add-invoice' === pathName || '/edit-invoice'
                             === pathName ? 'active submenu' : 'submenu' }`}>          
                                <Link to="#" className={isSideMenu == "invoice" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu =="invoice" ? "": "invoice")}><FeatherIcon icon="clipboard" /> <span> Invoices</span><span className="menu-arrow"></span></Link>                               
                                    { isSideMenu == "invoice" ? 
                                        <ul>
                                            <li className={`${'/invoices' === pathName ? 'active' : '' }`}><Link to="/invoices">Invoices List</Link></li>
                                            <li className={`${'/invoice-grid' === pathName ? 'active' : '' }`}><Link to="/invoice-grid">Invoices Grid</Link></li>
                                            <li className={`${'/add-invoice' === pathName ? 'active' : '' }`}><Link to="/add-invoice">Add Invoices</Link></li>
                                            <li className={`${'/edit-invoice' === pathName ? 'active' : '' }`}><Link to="/edit-invoice">Edit Invoices</Link></li>
                                            <li className={`${'/invoice-details' === pathName ? 'active' : '' }`}><Link to="/invoice-details">Invoices Details</Link></li>
                                            <li className={`${'/invoices-settings' === pathName ? 'active' : '' }`}><Link to="/invoices-settings">Invoices Settings</Link></li>
                                        </ul>
										:"" 
                                    }
                            </li> 
                            <li className={`${'/payments' === pathName || '/add-payments' === pathName ? 'active' : '' }`}>
                                <Link to="/payments"><FeatherIcon icon="credit-card" /> <span>Payments</span></Link>
                            </li>
                            <li className={`${'/expenses' === pathName || '/add-expenses' === pathName  || '/edit-expenses' === pathName  ? 'active' : '' }`}>
                                <Link to="/expenses"><FeatherIcon icon="package" /> <span>Expenses</span></Link>
                            </li>
                            <li className={`${'/sales-report' === pathName || '/expenses-report' === pathName || '/profit-loss-report' === pathName
                             || '/taxs-report' === pathName ? 'active submenu' : 'submenu' }`}>          
                                <Link to="#" className={isSideMenu == "report" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu =="report" ? "": "report")}><FeatherIcon icon="pie-chart" /> <span> Reports</span><span className="menu-arrow"></span></Link>                               
                                    { isSideMenu == "report" ? 
                                        <ul>
                                            <li className={`${'/sales-report' === pathName ? 'active' : '' }`}><Link to="/sales-report">Sales Report</Link></li>
                                            <li className={`${'/expenses-report' === pathName ? 'active' : '' }`}><Link to="/expenses-report">Expenses Report</Link></li>
                                            <li className={`${'/profit-loss-report' === pathName ? 'active' : '' }`}><Link to="/profit-loss-report">Profit &amp; Loss Report</Link></li>
                                            <li className={`${'/taxs-report' === pathName ? 'active' : '' }`}><Link to="/taxs-report">Taxs Report</Link></li>
                                        </ul>
										:"" 
                                    }
                            </li>                            
                            <li className={`${'/settings' === pathName || '/preferences' === pathName || '/tax-types' === pathName ||  '/expense-category' === pathName ||  '/notifications' === pathName ||  '/change-password' === pathName ||  '/delete-account' === pathName ? 'active' : '' }`}>
                                <Link to="/settings"><FeatherIcon icon="settings" /> <span>Settings</span></Link>
                            </li>
                            <li className={`${'/chat' === pathName || '/calendar' === pathName || '/inbox' === pathName ? 'active submenu' : 'submenu' }`}>                            
                                <Link to="#" className={isSideMenu == "application" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu =="application" ? "": "application")}><FeatherIcon icon="grid" /> <span> Application</span> <span className="menu-arrow"></span></Link>
                                {
                                  isSideMenu ==  "application" ? 
                                  <ul>
                                        <li className={`${'/chat' === pathName ? 'active' : '' }`}><Link to="/chat">Chat</Link></li>
                                        <li className={`${'/calendar' === pathName ? 'active' : '' }`}><Link to="/calendar">Calendar</Link></li>
                                        <li className={`${'/inbox' === pathName ? 'active' : '' }`}><Link to="/inbox">Email</Link></li>
                                    </ul> : ""
                                }
                               
                            </li>
                            <li className="menu-title"> 
                                <span>Pages</span>
                            </li>
                            <li className={`${'/profile' === pathName ? 'active' : '' }`}> 
                                <Link to="/profile"><FeatherIcon icon="user-plus" /> <span>Profile</span></Link>
                            </li>
                            <li className={`${'/login' === pathName || '/register' === pathName || '/forgot-password' === pathName || '/lock-screen' === pathName ? 'active submenu' : 'submenu' }`}>
                                <Link to="#" className={isSideMenu == "authentication" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu =="authentication" ? "": "authentication")} ><FeatherIcon icon="lock" /> <span> Authentication </span> <span className="menu-arrow"></span></Link>
                                {
                                  isSideMenu ==  "authentication" ? 
                                <ul>
                                    <li className={`${'/login' === pathName ? 'active' : '' }`}><Link to="/login"> Login </Link></li>
                                    <li className={`${'/register' === pathName ? 'active' : '' }`}><Link to="/register"> Register </Link></li>
                                    <li className={`${'/forgot-password' === pathName ? 'active' : '' }`}><Link to="/forgot-password"> Forgot Password </Link></li>
                                    <li className={`${'/lock-screen' === pathName ? 'active' : '' }`}><Link to="/lock-screen"> Lock Screen </Link></li>
                                </ul> : ""
                                }
                            </li>
                            <li className={`${'/error-404' === pathName || '/error-500' === pathName  ? 'active submenu' : 'submenu' }`}>
                                <Link to="#" className={isSideMenu == "errorPages" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu =="errorPages" ? "": "errorPages")}><FeatherIcon icon="alert-octagon" />  <span> Error Pages </span> <span className="menu-arrow"></span></Link>
                                {
                                  isSideMenu ==  "errorPages" ? 
                                <ul>
                                    <li className={`${'/error-404' === pathName ? 'active' : '' }`}><Link to="/error-404">404 Error </Link></li>
                                    <li className={`${'/error-500' === pathName ? 'active' : '' }`}><Link to="/error-500">500 Error </Link></li>
                                </ul> : ""
                                }
                            </li>
                            <li className={`${'/users' === pathName ? 'active' : '' }`}> 
                                <Link to="/users"><FeatherIcon icon="users" /> <span>Users</span></Link>
                            </li>
                            <li className={`${'/blank-page' === pathName ? 'active' : '' }`}> 
                                <Link to="/blank-page"><FeatherIcon icon="file" /> <span>Blank Page</span></Link>
                            </li>
                            <li className={`${'/maps-vector' === pathName ? 'active' : '' }`}> 
                                <Link to="/maps-vector"><FeatherIcon icon="map-pin" /> <span>Vector Maps</span></Link>
                            </li>
                            <li className="menu-title"> 
                                <span>UI Interface</span>
                            </li>
                            <li className={`${'/components' === pathName ? 'active' : '' }`}> 
                                <Link to="/components"><FeatherIcon icon="layers" /> <span>Components</span></Link>
                            </li>
                            <li className={`${'/form-basic-inputs' === pathName || '/form-input-groups' === pathName || '/form-horizontal' === pathName || '/form-vertical' === pathName ||  '/form-mask' === pathName ||  '/form-validation' === pathName ? 'active submenu' : 'submenu' }`}>
                                <Link to="#" className={isSideMenu == "forms" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu =="forms" ? "": "forms")}><FeatherIcon icon="file-minus" /> <span> Forms </span> <span className="menu-arrow"></span></Link>
                                {
                                  isSideMenu ==  "forms" ? 
                                <ul>
                                    <li className={`${'/form-basic-inputs' === pathName ? 'active' : '' }`}><Link to="/form-basic-inputs">Basic Inputs </Link></li>
                                    <li className={`${'/form-input-groups' === pathName ? 'active' : '' }`}><Link to="/form-input-groups">Input Groups </Link></li>
                                    <li className={`${'/form-horizontal' === pathName ? 'active' : '' }`}><Link to="/form-horizontal">Horizontal Form </Link></li>
                                    <li className={`${'/form-vertical' === pathName ? 'active' : '' }`}><Link to="/form-vertical"> Vertical Form </Link></li>
                                    <li className={`${'/form-mask' === pathName ? 'active' : '' }`}><Link to="/form-mask"> Form Mask </Link></li>
                                    <li className={`${'/form-validation' === pathName ? 'active' : '' }`}><Link to="/form-validation"> Form Validation </Link></li>
                                </ul> :""
                                }
                            </li>
                            <li className={`${'/tables-basic' === pathName || '/data-tables' === pathName ? 'active submenu' : 'submenu' }`}>
                                <Link to="#" className={isSideMenu == "tables" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu =="tables" ? "": "tables")}><FeatherIcon icon="layout" />  <span> Tables </span> <span className="menu-arrow"></span></Link>
                                {
                                  isSideMenu ==  "tables" ?
                                <ul>
                                    <li className={`${'/tables-basic' === pathName ? 'active' : '' }`}><Link to="/tables-basic">Basic Tables </Link></li>
                                    <li className={`${'/data-tables' === pathName ? 'active' : '' }`}><Link to="/data-tables">Data Table </Link></li>
                                </ul> :""
                                }
                            </li>
                        </ul>
                    </div>
                </div>
                </Scrollbars>
            </div>
       
        );
    
}
export default withRouter(Sidebar);
