// reactjs-files/template-rtl/src/invoices/AddInvoice.jsx
import React, {useState, useEffect} from 'react'
import { Link } from 'react-router-dom';
import Select2 from 'react-select2-wrapper';
import DatePicker from 'react-datepicker';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import {Logo,signature,circle1,circle2} from "../_components/imagepath"
import FeatherIcon from 'feather-icons-react';

const AddInvoice = () => {
	
	const [show, setShow] = useState(true);
    const[task,settask]=useState(true);
    const [menu, setMenu] = useState(false)
	const [date, setDate] = useState(new Date());
    const ontaskClick = () =>{
        settask(!task)
      }
	const toggleMobileMenu = () => {
		setMenu(!menu)
	  }
    
    useEffect(() => {
        let elements = Array.from(document.getElementsByClassName('react-datepicker-wrapper'));
        elements.map(element => element.classList.add("width-100"))
	},[]);

	
    const handleChange = (date) => {
        setDate(date)
    };

        return (

            <>
            <div className={`main-wrapper ${menu ? 'slide-nav': ''}`}> 
          
          <Header onMenuClick={(value) => toggleMobileMenu()} />
          <Sidebar /> 
          {/* <!-- Page Wrapper --> */}
			<div className="page-wrapper">
				<div className="content container-fluid">
			
					{/* <!-- Page Header --> */}
					<div className="page-header invoices-page-header">
						<div className="row align-items-center">
							<div className="col">
								<ul className="breadcrumb invoices-breadcrumb">
									<li className="breadcrumb-item invoices-breadcrumb-item">
										<Link to="/invoices">
											<i className="fe fe-chevron-left"><FeatherIcon icon="chevron-left"/> </i>Back to Invoice List
										</Link >
									</li>
								</ul>
							</div>
							<div className="col-auto">
								<div className="invoices-create-btn">
									<Link className="invoices-preview-link" to="#" data-bs-toggle="modal" data-bs-target="#invoices_preview"><i className="fe fe-eye"> <FeatherIcon icon="eye"/></i> Preview</Link >
									<Link to="#" data-bs-toggle="modal" data-bs-target="#delete_invoices_details" className="btn delete-invoice-btn">
										Delete Invoice
									</Link >
									<Link to="#" data-bs-toggle="modal" data-bs-target="#save_invocies_details" className="btn save-invoice-btn">
										Save Draft
									</Link >
								</div>
							</div>
						</div>
					</div>
					{/* <!-- /Page Header --> */}
					
					<div className="row">
						<div className="col-md-12">
							<div className="card invoices-add-card">
								<div className="card-body">
									<form action="#" className="invoices-form">
										<div className="invoices-main-form">
											<div className="row">
												<div className="col-xl-4 col-md-6 col-sm-12 col-12">
													<div className="form-group">
														<label>Customer Name</label>
														<div className="multipleSelection">
															<div className="selectBox"  onClick={() => setShow((s) => !s)}>
																<p className="mb-0">Select Customer</p>
																<span className="down-icon"><FeatherIcon icon="chevron-down" /></span>
															</div>						  
															<div id="checkBoxes-one" style={{ display: show ? "none" : "block" }}>
																<p className="checkbox-title">Customer Search</p>
																<div className="form-custom">
																	<input type="text" className="form-control bg-grey" placeholder="Enter Customer Name"/>
																</div>
																<div className="selectBox-cont">
																	<label className="custom_check w-100">
																		<input type="checkbox" name="username"/>
																		<span className="checkmark"></span>  Brian Johnson
																	</label>
																	<label className="custom_check w-100">
																		<input type="checkbox" name="username"/>
																		<span className="checkmark"></span>  Russell Copeland
																	</label>
																	<label className="custom_check w-100">
																		<input type="checkbox" name="username"/>
																		<span className="checkmark"></span>  Greg Lynch
																	</label>
																	<label className="custom_check w-100">
																		<input type="checkbox" name="username"/>
																		<span className="checkmark"></span> John Blair
																	</label>
																	<label className="custom_check w-100">
																		<input type="checkbox" name="username"/>
																		<span className="checkmark"></span> Barbara Moore
																	</label>
																	<label className="custom_check w-100">
																		<input type="checkbox" name="username"/>
																		<span className="checkmark"></span> Hendry Evan
																	</label>
																	<label className="custom_check w-100">
																		<input type="checkbox" name="username"/>
																		<span className="checkmark"></span> Richard Miles
																	</label>
																</div>
																<button type="submit" className="btn w-100 btn-primary">Apply</button>
																<button type="reset" className="btn w-100 btn-grey">Reset</button>
															</div>
														</div>
													</div>
													<div className="form-group">
														<label>Po Number</label>
														<input className="form-control" type="text" placeholder="Enter Reference Number"/>
													</div>
												</div>
												<div className="col-xl-5 col-md-6 col-sm-12 col-12">
													<h4 className="invoice-details-title">Invoice details</h4>
													<div className="invoice-details-box">
														<div className="invoice-inner-footer">
															<div className="row align-items-center">
																<div className="col-lg-6 col-md-6">
																	<div className="invoice-inner-date">
																		<span>
																			Date <DatePicker selected={date} onChange={handleChange} className="form-control datetimepicker" value="15/02/2022"  />
																		</span>
																	</div>
																</div>
																<div className="col-lg-6 col-md-6">
																	<div className="invoice-inner-date invoice-inner-datepic">
																		<span>
																			Due Date <DatePicker selected={date} onChange={handleChange} className="form-control datetimepicker" type="text" value="Select" />
																		</span>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
												<div className="col-xl-3 col-md-12 col-sm-12 col-12">
													<div className="inovices-month-info">
														<div className="form-group mb-0">
															<label className="custom_check w-100">
																<input type="checkbox" id="enableTax" name="invoice"/>
																<span className="checkmark"></span> Enable tax
															</label>
															<label className="custom_check w-100">
																<input type="checkbox" id="chkYes" name="invoice"/>
																<span className="checkmark"></span> Recurring Invoice
															</label>
														</div>
														<div id="show-invoices">
															<div className="row">
																<div className="col-md-6">
																	<div className="form-group">
																		<select className="select">
																			<option>By month</option>
																			<option>March</option>
																			<option>April</option>
																			<option>May</option>
																			<option>June</option>
																			<option>July</option>
																		</select>
																	</div>
																</div>
																<div className="col-md-6">
																	<div className="form-group">
																		<input className="form-control" type="text" placeholder="Enter Months"/>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div className="invoice-item">
											<div className="row">
												<div className="col-xl-4 col-lg-6 col-md-6">
													<div className="invoice-info">
														<strong className="customer-text">Invoice From <Link className="small" to="/edit-invoice">Edit Address</Link ></strong>
														<p className="invoice-details invoice-details-two">
															Darren Elder <br />
															806  Twin Willow Lane, Old Forge,<br />
															Newyork, USA <br />
														</p>
													</div>
												</div>
												<div className="col-xl-4 col-lg-6 col-md-6">
													<div className="invoice-info">
														<strong className="customer-text">Invoice To</strong>
														<p className="invoice-details invoice-details-two">
															Walter Roberson <br />
															299 Star Trek Drive, Panama City, <br />
															Florida, 32405, USA <br />
														</p>
													</div>
												</div>
											</div>
										</div>
										<div className="invoice-add-table">
											<h4>Item Details</h4>
											<div className="table-responsive">
												<table className="table table-center add-table-items">
													<thead>
														<tr>
															<th>Items</th>
															<th>Category</th>
															<th>Quantity</th>
															<th>Price</th>
															<th>Amount</th>
															<th>Discount</th>
															<th>Actions</th>
														</tr>
													</thead>
													<tbody>
														<tr className="add-row">
															<td>
																<input type="text" className="form-control"/>
															</td>
															<td>
																<input type="text" className="form-control"/>
															</td>
															<td>
																<input type="text" className="form-control"/>
															</td>
															<td>
																<input type="text" className="form-control"/>
															</td>
															<td>
																<input type="text" className="form-control"/>
															</td>
															<td>
																<input type="text" className="form-control"/>
															</td>
															<td className="add-remove text-end">
																<Link to="javascript:void(0);" className="add-btn ms-2"><i className="fas fa-plus-circle"></i></Link > 
																<Link to="#" className="copy-btn ms-2"><i className="fe fe-copy"></i></Link ><Link to="javascript:void(0);" className="remove-btn"><i className="fe fe-trash-2"></i></Link >
															</td>
														</tr>
													</tbody>
												</table>
											</div>
										</div>
										<div className="row">
											<div className="col-lg-7 col-md-6">
												<div className="invoice-fields">
													<h4 className="field-title">More Fields</h4>
													<div className="field-box">
														<p>Payment Details</p>
														<Link className="btn btn-primary" to="#" data-bs-toggle="modal" data-bs-target="#bank_details"><i className="fas fa-plus-circle ms-2"></i>Add Bank Details</Link >
													</div>
												</div>
												<div className="invoice-faq">
													<div className="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
														<div className="faq-tab">
															<div className="panel panel-default">
																<div className="panel-heading" role="tab" id="headingTwo">
																	<p className="panel-title">
																		<a className="collapsed" data-bs-toggle="collapse" data-bs-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
																		<i className="fas fa-plus-circle me-1"></i> Add Terms & Conditions
																		</a >
																	</p>
																</div>
																<div id="collapseTwo" className="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" data-bs-parent="#accordion">
																	<div className="panel-body">
																		<textarea className="form-control"></textarea>
																	</div>
																</div>
															</div>
														</div>
														<div className="faq-tab">
															<div className="panel panel-default">
																<div className="panel-heading" role="tab" id="headingThree">
																	<p className="panel-title">
																		<a className="collapsed" data-bs-toggle="collapse" data-bs-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
																		<i className="fas fa-plus-circle me-1"></i> Add Notes
																		</a>
																	</p>
																</div>
																<div id="collapseThree" className="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree" data-bs-parent="#accordion">
																	<div className="panel-body">
																		<textarea className="form-control"></textarea>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div className="col-lg-5 col-md-6">
												<div className="invoice-total-card">
													<h4 className="invoice-total-title">Summary</h4>
													<div className="invoice-total-box">
														<div className="invoice-total-inner">
															<p>Taxable Amount <span>$21</span></p>
															<p>Round Off 
																<input type="checkbox" id="status_1" className="check"/>
																<label htmlFor="status_1" className="checktoggle">checkbox</label> 
																<span>$54</span>
															</p>
															<div className="links-info-one">
																<div className="links-info">
																	<div className="links-cont">
																		<Link to="#" className="service-trash">
																			<i className="feather-trash-2"></i>
																		</Link >
																	</div>
																</div>
															</div>
															<Link to="javascript:void(0);" className="add-links">
																<i className="fas fa-plus-circle me-1"></i> Additional Charges
															</Link >
															<div className="links-info-discount">
																<div className="links-cont-discount">
																	<Link to="javascript:void(0);" className="add-links-one">
																		<i className="fas fa-plus-circle me-1"></i> Add more Discount
																	</Link >
																	<Link to="#" className="service-trash-one">
																		<i className="feather-trash-2"></i>
																	</Link >
																</div>
															</div>
														</div>
														<div className="invoice-total-footer">
															<h4>Total Amount <span>$ 894.00</span></h4>
														</div>
													</div>
												</div>
												<div className="upload-sign">
													<div className="form-group service-upload">
														<span>Upload Sign</span>
														<input type="file" multiple/>
													</div>
													<div className="form-group">
														<input type="text" className="form-control" placeholder="Name of the Signatuaory"/>
													</div>
													<div className="form-group float-end mb-0">
														<button className="btn btn-primary" type="submit">Save Invoice</button>
													</div>
												</div>
											</div>
										</div>
									</form>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{/* <!-- /Page Wrapper -->

		    <!-- Invoices Preview Modal --> */}
			<div className="modal custom-modal fade invoices-preview" id="invoices_preview" role="dialog">
				<div className="modal-dialog modal-dialog-centered modal-xl">
					<div className="modal-content">
						<div className="modal-body">
							<div className="row justify-content-center">
								<div className="col-lg-12">
									<div className="card invoice-info-card">
										<div className="card-body pb-0">
											<div className="invoice-item invoice-item-one">
												<div className="row">
													<div className="col-md-6">
														<div className="invoice-logo">
															<img src={Logo} alt="logo"/>
														</div>
													</div>
													<div className="col-md-6">
														<div className="invoice-info">
															<div className="invoice-head">
																<h2 className="text-primary">Invoice</h2>
																<p>Invoice Number : In983248782</p>
															</div>
														</div>
													</div>
												</div>
											</div>
											
											{/* <!-- Invoice Item --> */}
											<div className="invoice-item invoice-item-bg">
												<div className="invoice-circle-img">
													<img src={circle1} alt="" className="invoice-circle1"/>
													<img src={circle2} alt="" className="invoice-circle2"/>
												</div>
												<div className="row">
													<div className="col-lg-4 col-md-12">
														<div className="invoice-info">
															<strong className="customer-text-one">Billed to</strong>
															<h6 className="invoice-name">Customer Name</h6>
															<p className="invoice-details invoice-details-two">
																9087484288 <br />
																Address line 1, <br />
																Address line 2 <br />
																Zip code ,City - Country
															</p>
														</div>
													</div>
													<div className="col-lg-4 col-md-12">
														<div className="invoice-info">
															<strong className="customer-text-one">Invoice From</strong>
															<h6 className="invoice-name">Company Name</h6>
															<p className="invoice-details invoice-details-two">
																9087484288 <br />
																Address line 1, <br />
																Address line 2 <br />
																Zip code ,City - Country
															</p>
														</div>
													</div>
													<div className="col-lg-4 col-md-12">
														<div className="invoice-info invoice-info-one border-0">
															<p>Issue Date : 27 Jul 2022</p>
															<p>Due Date : 27 Aug 2022</p>
															<p>Due Amount : $ 1,54,22 </p>
															<p>Recurring Invoice : 15 Months</p>
															<p className="mb-0">PO Number : 54515454</p>
														</div>
													</div>
												</div>
											</div>
											{/* <!-- /Invoice Item -->

											<!-- Invoice Item --> */}
											<div className="invoice-item invoice-table-wrap">
												<div className="row">
													<div className="col-md-12">
														<div className="table-responsive">
															<table className="invoice-table table table-center mb-0">
																<thead>
																	<tr>
																		<th>Description</th>
																		<th>Category</th>
																		<th>Rate/Item</th>
																		<th>Quantity</th>
																		<th>Discount (%)</th>
																		<th className="text-end">Amount</th>
																	</tr>
																</thead>
																<tbody>
																	<tr>
																		<td>Dell Laptop</td>
																		<td>Laptop</td>
																		<td>$1,110</td>
																		<th>2</th>
																		<th>2%</th>
																		<td className="text-end">$400</td>
																	</tr>
																	<tr>
																		<td>HP Laptop</td>
																		<td>Laptop</td>
																		<td>$1,500</td>
																		<th>3</th>
																		<th>6%</th>
																		<td className="text-end">$3,000</td>
																	</tr>
																	<tr>
																		<td>Apple Ipad</td>
																		<td>Ipad</td>
																		<td>$11,500</td>
																		<th>1</th>
																		<th>10%</th>
																		<td className="text-end">$11,000</td>
																	</tr>
																</tbody>
															</table>
														</div>
													</div>
												</div>
											</div>
											{/* <!-- /Invoice Item --> */}

											<div className="row align-items-center justify-content-center">
												<div className="col-lg-6 col-md-6">
													<div className="invoice-payment-box">
														<h4>Payment Details</h4>
														<div className="payment-details">
															<p>Debit Card XXXXXXXXXXXX-2541 HDFC Bank</p>
														</div>
													</div>
												</div>
												<div className="col-lg-6 col-md-6">
													<div className="invoice-total-card">
														<div className="invoice-total-box">
															<div className="invoice-total-inner">
																<p>Taxable <span>$6,660.00</span></p>
																<p>Additional Charges <span>$6,660.00</span></p>
																<p>Discount <span>$3,300.00</span></p>
																<p className="mb-0">Sub total <span>$3,300.00</span></p>
															</div>
															<div className="invoice-total-footer">
																<h4>Total Amount <span>$143,300.00</span></h4>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div className="invoice-sign-box">
												<div className="row">
													<div className="col-lg-8 col-md-8">
														<div className="invoice-terms">
															<h6>Notes:</h6>
															<p className="mb-0">Enter customer notes or any other details</p>
														</div>
														<div className="invoice-terms mb-0">
															<h6>Terms and Conditions:</h6>
															<p className="mb-0">Enter customer notes or any other details</p>
														</div>
													</div>
													<div className="col-lg-4 col-md-4">
														<div className="invoice-sign text-end">
															<img className="img-fluid d-inline-block" src={signature} alt="sign"/>
															<span className="d-block">Harristemp</span>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{/* <!-- /Invoices Preview Modal -->

		    <!-- Add Invoices Modal --> */}
			<div className="modal custom-modal fade bank-details" id="bank_details" role="dialog">
				<div className="modal-dialog modal-dialog-centered modal-lg">
					<div className="modal-content">
						<div className="modal-header">
							<div className="form-header text-start mb-0">
								<h4 className="mb-0">Add Bank Details</h4>
							</div>
							<button type="button" className="close" data-bs-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div className="modal-body">
							<div className="bank-inner-details">
								<div className="row">
									<div className="col-lg-6 col-md-6">
										<div className="form-group">
											<label>Account Holder Name</label>
											<input type="text" className="form-control" placeholder="Add Name"/>
										</div>
									</div>
									<div className="col-lg-6 col-md-6">
										<div className="form-group">
											<label>Bank name</label>
											<input type="text" className="form-control" placeholder="Add Bank name"/>
										</div>
									</div>
									<div className="col-lg-6 col-md-6">
										<div className="form-group">
											<label>IFSC Code</label>
											<input type="text" className="form-control"/>
										</div>
									</div>
									<div className="col-lg-6 col-md-6">
										<div className="form-group">
											<label>Account Number</label>
											<input type="text" className="form-control"/>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div className="modal-footer">
							<div className="bank-details-btn">
								<Link to="javascript:void(0);" data-bs-dismiss="modal" className="btn bank-cancel-btn ms-2">Cancel</Link >
								<Link to="javascript:void(0);" className="btn bank-save-btn">Save Item</Link >
							</div>
						</div>
					</div>
				</div>
			</div>
			{/* <!-- /Add Invoices Modal -->

			<!-- Delete Invoices Modal --> */}
			<div className="modal custom-modal fade" id="delete_invoices_details" role="dialog">
				<div className="modal-dialog modal-dialog-centered">
					<div className="modal-content">
						<div className="modal-body">
							<div className="form-header">
								<h3>Delete Invoice Details</h3>
								<p>Are you sure want to delete?</p>
							</div>
							<div className="modal-btn delete-action">
								<div className="row">
									<div className="col-6">
										<Link to="javascript:void(0);" data-bs-dismiss="modal" className="btn btn-primary paid-continue-btn">Delete</Link >
									</div>
									<div className="col-6">
										<Link to="javascript:void(0);" data-bs-dismiss="modal" className="btn btn-primary paid-cancel-btn">Cancel</Link >
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{/* <!-- /Delete Invoices Modal -->

			<!-- Save Invoices Modal --> */}
			<div className="modal custom-modal fade" id="save_invocies_details" role="dialog">
				<div className="modal-dialog modal-dialog-centered">
					<div className="modal-content">
						<div className="modal-body">
							<div className="form-header">
								<h3>Save Invoice Details</h3>
								<p>Are you sure want to save?</p>
							</div>
							<div className="modal-btn delete-action">
								<div className="row">
									<div className="col-6">
										<Link to="javascript:void(0);" data-bs-dismiss="modal" className="btn btn-primary paid-continue-btn">Save</Link >
									</div>
									<div className="col-6">
										<Link to="javascript:void(0);" data-bs-dismiss="modal" className="btn btn-primary paid-cancel-btn">Cancel</Link >
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{/* <!-- /Save Invoices Modal --> */}
             </div>
                </>
        );
    }
    export default AddInvoice

// angular-files/template/src/app/add-invoice/add-invoice.component.ts
import { Component, OnInit, TemplateRef } from '@angular/core';
import { CommonServiceService } from '../common-service.service';
import { Event, Router, NavigationStart, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { FormBuilder, FormGroup, Validators } from "@angular/forms";
import { AllModulesService } from '../all-modules.service';
import { ToastrService } from 'ngx-toastr';
import { DatePipe } from "@angular/common";
declare const $: any;

@Component({
  selector: 'app-add-invoice',
  templateUrl: './add-invoice.component.html',
  styleUrls: ['./add-invoice.component.css']
})
export class AddInvoiceComponent implements OnInit {
  public url: any = "invoices";
  public addEstimateForm: FormGroup;
  public pipe = new DatePipe("en-US");
  constructor(public router: Router, location: Location, private allModulesService: AllModulesService,private formBuilder: FormBuilder,private route: ActivatedRoute,private toastr: ToastrService) { 
  }

  ngOnInit() {

    this.addEstimateForm = this.formBuilder.group({
      customerName: ["", [Validators.required]],
      estimateFrom: ["", [Validators.required]],
      estimateTo: ["", [Validators.required]],
      estimateNumber: ["", [Validators.required]],
      customerRef: ["", [Validators.required]],
    });
      // Datetimepicker
  
  if($('.datetimepicker').length > 0 ){
    $('.datetimepicker').datetimepicker({
      format: 'DD-MM-YYYY',
      icons: {
        up: "fas fa-angle-up",
        down: "fas fa-angle-down",
        next: 'fas fa-angle-right',
        previous: 'fas fa-angle-left'
      }
    });
  }
  }
  private markFormGroupTouched(formGroup: FormGroup) {
    (<any>Object).values(formGroup.controls).forEach((control) => {
      control.markAsTouched();
      if (control.controls) {
        this.markFormGroupTouched(control);
      }
    });
  }
  addEstimate() {
    if(this.addEstimateForm.invalid){
      this.markFormGroupTouched(this.addEstimateForm)
      return
    }
    else{
      const jDate = new Date(this.addEstimateForm.value.estimateFrom.year, this.addEstimateForm.value.estimateFrom.month - 1, this.addEstimateForm.value.estimateFrom.day);
      const eDate = new Date(this.addEstimateForm.value.estimateTo.year, this.addEstimateForm.value.estimateTo.month - 1, this.addEstimateForm.value.estimateTo.day);
      let DateJoin = this.pipe.transform(jDate,"dd-MM-yyyy");
      let DateExpiry = this.pipe.transform(eDate,"dd-MM-yyyy");
      let obj = {
        customer_name : this.addEstimateForm.value.customerName,
        number: this.addEstimateForm.value.estimateNumber,
        created_date : DateJoin,
        due_date : DateExpiry,
        paid_on: DateJoin,
        amount : "$100",
        status : "Paid",
      };
      this.allModulesService.add(obj, this.url).subscribe((data) => {
        
      });
      this.router.navigate(["/invoice-reports"]);
      this.toastr.success("Invoice added sucessfully...!", "Success");
    }
  }
  ngAfterViewInit() {
    this.loadfeather("assets/plugins/icons/feather/feather.css")
  }
  loadfeather(js) {
    var script = document.createElement('link');
    script.href = js;
    script.rel = "stylesheet"
    document.head.appendChild(script);
  }
}

<!-- Page Wrapper -->
<div class="page-wrapper">
	<div class="content container-fluid">

		<!-- Page Header -->
		<div class="page-header invoices-page-header">
			<div class="row align-items-center">
				<div class="col">
					<ul class="breadcrumb invoices-breadcrumb">
						<li class="breadcrumb-item invoices-breadcrumb-item">
							<a [routerLink]="'/invoices-list'">
								<i class="fe fe-chevron-left"></i> Back to Invoice List
							</a>
						</li>
					</ul>
				</div>
				<div class="col-auto">
					<div class="invoices-create-btn">
						<a class="invoices-preview-link" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#invoices_preview"><i class="fe fe-eye"></i> Preview</a>
						<a  href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#delete_invoices_details" class="btn delete-invoice-btn">
							Delete Invoice
						</a>
						<a href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#save_invocies_details" class="btn save-invoice-btn">
							Save Draft
						</a>
					</div>
				</div>
			</div>
		</div>
		<!-- /Page Header -->
		
		<div class="row">
			<div class="col-md-12">
				<div class="card invoices-add-card">
					<div class="card-body">
						<form action="#" class="invoices-form">
							<div class="invoices-main-form">
								<div class="row">
									<div class="col-xl-4 col-md-6 col-sm-12 col-12">
										<div class="form-group">
											<label>Customer Name</label>
											<div class="multipleSelection">
												<div class="selectBox">
													<p class="mb-0">Select Customer</p>
													<span class="down-icon"><i data-feather="chevron-down"></i></span>
												</div>						  
												<div id="checkBoxes-one">
													<p class="checkbox-title">Customer Search</p>
													<div class="form-custom">
														<input type="text" class="form-control bg-grey" placeholder="Enter Customer Name">
													</div>
													<div class="selectBox-cont">
														<label class="custom_check w-100">
															<input type="checkbox" name="username">
															<span class="checkmark"></span>  Brian Johnson
														</label>
														<label class="custom_check w-100">
															<input type="checkbox" name="username">
															<span class="checkmark"></span>  Russell Copeland
														</label>
														<label class="custom_check w-100">
															<input type="checkbox" name="username">
															<span class="checkmark"></span>  Greg Lynch
														</label>
														<label class="custom_check w-100">
															<input type="checkbox" name="username">
															<span class="checkmark"></span> John Blair
														</label>
														<label class="custom_check w-100">
															<input type="checkbox" name="username">
															<span class="checkmark"></span> Barbara Moore
														</label>
														<label class="custom_check w-100">
															<input type="checkbox" name="username">
															<span class="checkmark"></span> Hendry Evan
														</label>
														<label class="custom_check w-100">
															<input type="checkbox" name="username">
															<span class="checkmark"></span> Richard Miles
														</label>
													</div>
													<button type="submit" class="btn w-100 btn-primary">Apply</button>
													<button type="reset" class="btn w-100 btn-grey">Reset</button>
												</div>
											</div>
										</div>
										<div class="form-group">
											<label>Po Number</label>
											<input class="form-control" type="text" placeholder="Enter Reference Number">
										</div>
									</div>
									<div class="col-xl-5 col-md-6 col-sm-12 col-12">
										<h4 class="invoice-details-title">Invoice details</h4>
										<div class="invoice-details-box">
											<div class="invoice-inner-head">
												<span>Invoice No. <a [routerLink]="'/view-invoice'">IN093439#@09</a></span>
											</div>
											<div class="invoice-inner-footer">
												<div class="row align-items-center">
													<div class="col-lg-6 col-md-6">
														<div class="invoice-inner-date">
															<span>
																Date <input class="form-control datetimepicker" type="text" placeholder="15/02/2022">
															</span>
														</div>
													</div>
													<div class="col-lg-6 col-md-6">
														<div class="invoice-inner-date invoice-inner-datepic">
															<span>
																Due Date <input class="form-control datetimepicker" type="text" placeholder="Select">
															</span>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="col-xl-3 col-md-12 col-sm-12 col-12">
										<div class="inovices-month-info">
											<div class="form-group mb-0">
												<label class="custom_check w-100">
													<input type="checkbox" id="enableTax" name="invoice">
													<span class="checkmark"></span> Enable tax
												</label>
												<label class="custom_check w-100">
													<input type="checkbox" id="chkYes" name="invoice">
													<span class="checkmark"></span> Recurring Invoice
												</label>
											</div>
											<div id="show-invoices">
												<div class="row">
													<div class="col-md-6">
														<div class="form-group">
															<select class="select">
																<option>By month</option>
																<option>March</option>
																<option>April</option>
																<option>May</option>
																<option>June</option>
																<option>July</option>
															</select>
														</div>
													</div>
													<div class="col-md-6">
														<div class="form-group">
															<input class="form-control" type="text" placeholder="Enter Months">
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="invoice-item">
								<div class="row">
									<div class="col-xl-4 col-lg-6 col-md-6">
										<div class="invoice-info">
											<strong class="customer-text">Invoice From <a class="small" [routerLink]="'/edit-invoice'">Edit Address</a></strong>
											<p class="invoice-details invoice-details-two">
												Darren Elder <br>
												806  Twin Willow Lane, Old Forge,<br>
												Newyork, USA <br>
											</p>
										</div>
									</div>
									<div class="col-xl-4 col-lg-6 col-md-6">
										<div class="invoice-info">
											<strong class="customer-text">Invoice To</strong>
											<p class="invoice-details invoice-details-two">
												Walter Roberson <br>
												299 Star Trek Drive, Panama City, <br>
												Florida, 32405, USA <br>
											</p>
										</div>
									</div>
								</div>
							</div>
							<div class="invoice-add-table">
								<h4>Item Details</h4>
								<div class="table-responsive">
									<table class="table table-center add-table-items">
										<thead>
											<tr>
												<th>Items</th>
												<th>Category</th>
												<th>Quantity</th>
												<th>Price</th>
												<th>Amount</th>
												<th>Discount</th>
												<th>Actions</th>
											</tr>
										</thead>
										<tbody>
											<tr class="add-row">
												<td>
													<input type="text" class="form-control">
												</td>
												<td>
													<input type="text" class="form-control">
												</td>
												<td>
													<input type="text" class="form-control">
												</td>
												<td>
													<input type="text" class="form-control">
												</td>
												<td>
													<input type="text" class="form-control">
												</td>
												<td>
													<input type="text" class="form-control">
												</td>
												<td class="add-remove text-end">
													<a href="javascript:void(0);" class="add-btn me-2"><i class="fas fa-plus-circle"></i></a> 
													<a href="javascript:void(0);" class="copy-btn me-2"><i class="fe fe-copy"></i></a><a href="javascript:void(0);" class="remove-btn"><i class="fe fe-trash-2"></i></a>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
							<div class="row">
								<div class="col-lg-7 col-md-6">
									<div class="invoice-fields">
										<h4 class="field-title">More Fields</h4>
										<div class="field-box">
											<p>Payment Details</p>
											<a class="btn btn-primary" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#bank_details"><i class="fas fa-plus-circle me-2"></i>Add Bank Details</a>
										</div>
									</div>
									<div class="invoice-faq">
										<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
											<div class="faq-tab">
												<div class="panel panel-default">
													<div class="panel-heading" role="tab" id="headingTwo">
														<p class="panel-title">
															<a class="collapsed" data-bs-toggle="collapse" data-bs-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
															<i class="fas fa-plus-circle me-1"></i> Add Terms & Conditions
															</a>
														</p>
													</div>
													<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" data-bs-parent="#accordion">
														<div class="panel-body">
															<textarea class="form-control"></textarea>
														</div>
													</div>
												</div>
											</div>
											<div class="faq-tab">
												<div class="panel panel-default">
													<div class="panel-heading" role="tab" id="headingThree">
														<p class="panel-title">
															<a class="collapsed" data-bs-toggle="collapse" data-bs-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
															<i class="fas fa-plus-circle me-1"></i> Add Notes
															</a>
														</p>
													</div>
													<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree" data-bs-parent="#accordion">
														<div class="panel-body">
															<textarea class="form-control"></textarea>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-lg-5 col-md-6">
									<div class="invoice-total-card">
										<h4 class="invoice-total-title">Summary</h4>
										<div class="invoice-total-box">
											<div class="invoice-total-inner">
												<p>Taxable Amount <span>$21</span></p>
												<p>Round Off 
													<input type="checkbox" id="status_1" class="check">
													<label for="status_1" class="checktoggle">checkbox</label> 
													<span>$54</span>
												</p>
												<div class="links-info-one">
													<div class="links-info">
														<div class="links-cont">
															<a href="javascript:void(0);" class="service-trash">
																<i class="feather-trash-2"></i>
															</a>
														</div>
													</div>
												</div>
												<a href="javascript:void(0);" class="add-links">
													<i class="fas fa-plus-circle me-1"></i> Additional Charges
												</a>
												<div class="links-info-discount">
													<div class="links-cont-discount">
														<a href="javascript:void(0);" class="add-links-one">
															<i class="fas fa-plus-circle me-1"></i> Add more Discount
														</a>
														<a href="javascript:void(0);" class="service-trash-one">
															<i class="feather-trash-2"></i>
														</a>
													</div>
												</div>
											</div>
											<div class="invoice-total-footer">
												<h4>Total Amount <span>$ 894.00</span></h4>
											</div>
										</div>
									</div>
									<div class="upload-sign">
										<div class="form-group service-upload">
											<span>Upload Sign</span>
											<input type="file" multiple>
										</div>
										<div class="form-group">
											<input type="text" class="form-control" placeholder="Name of the Signatuaory">
										</div>
										<div class="form-group float-end mb-0">
											<button class="btn btn-primary" type="submit">Save Invoice</button>
										</div>
									</div>
								</div>
							</div>
						</form>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Page Wrapper -->

<!-- Invoices Preview Modal -->
<div class="modal custom-modal fade invoices-preview" id="invoices_preview" role="dialog">
	<div class="modal-dialog modal-dialog-centered modal-xl">
		<div class="modal-content">
			<div class="modal-body">
				<div class="row justify-content-center">
					<div class="col-lg-12">
						<div class="card invoice-info-card">
							<div class="card-body pb-0">
								<div class="invoice-item invoice-item-one">
									<div class="row">
										<div class="col-md-6">
											<div class="invoice-logo">
												<img src="assets/img/logo.png" alt="logo">
											</div>
										</div>
										<div class="col-md-6">
											<div class="invoice-info">
												<div class="invoice-head">
													<h2 class="text-primary">Invoice</h2>
													<p>Invoice Number : In983248782</p>
												</div>
											</div>
										</div>
									</div>
								</div>
								
								<!-- Invoice Item -->
								<div class="invoice-item invoice-item-bg">
									<div class="invoice-circle-img">
										<img src="assets/img/invoice-circle1.png" alt="" class="invoice-circle1">
										<img src="assets/img/invoice-circle2.png" alt="" class="invoice-circle2">
									</div>
									<div class="row">
										<div class="col-lg-4 col-md-12">
											<div class="invoice-info">
												<strong class="customer-text-one">Billed to</strong>
												<h6 class="invoice-name">Customer Name</h6>
												<p class="invoice-details invoice-details-two">
													9087484288 <br>
													Address line 1, <br>
													Address line 2 <br>
													Zip code ,City - Country
												</p>
											</div>
										</div>
										<div class="col-lg-4 col-md-12">
											<div class="invoice-info">
												<strong class="customer-text-one">Invoice From</strong>
												<h6 class="invoice-name">Company Name</h6>
												<p class="invoice-details invoice-details-two">
													9087484288 <br>
													Address line 1, <br>
													Address line 2 <br>
													Zip code ,City - Country
												</p>
											</div>
										</div>
										<div class="col-lg-4 col-md-12">
											<div class="invoice-info invoice-info-one border-0">
												<p>Issue Date : 27 Jul 2022</p>
												<p>Due Date : 27 Aug 2022</p>
												<p>Due Amount : $ 1,54,22 </p>
												<p>Recurring Invoice : 15 Months</p>
												<p class="mb-0">PO Number : 54515454</p>
											</div>
										</div>
									</div>
								</div>
								<!-- /Invoice Item -->

								<!-- Invoice Item -->
								<div class="invoice-item invoice-table-wrap">
									<div class="row">
										<div class="col-md-12">
											<div class="table-responsive">
												<table class="invoice-table table table-center mb-0">
													<thead>
														<tr>
															<th>Description</th>
															<th>Category</th>
															<th>Rate/Item</th>
															<th>Quantity</th>
															<th>Discount (%)</th>
															<th class="text-end">Amount</th>
														</tr>
													</thead>
													<tbody>
														<tr>
															<td>Dell Laptop</td>
															<td>Laptop</td>
															<td>$1,110</td>
															<th>2</th>
															<th>2%</th>
															<td class="text-end">$400</td>
														</tr>
														<tr>
															<td>HP Laptop</td>
															<td>Laptop</td>
															<td>$1,500</td>
															<th>3</th>
															<th>6%</th>
															<td class="text-end">$3,000</td>
														</tr>
														<tr>
															<td>Apple Ipad</td>
															<td>Ipad</td>
															<td>$11,500</td>
															<th>1</th>
															<th>10%</th>
															<td class="text-end">$11,000</td>
														</tr>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								<!-- /Invoice Item -->

								<div class="row align-items-center justify-content-center">
									<div class="col-lg-6 col-md-6">
										<div class="invoice-payment-box">
											<h4>Payment Details</h4>
											<div class="payment-details">
												<p>Debit Card XXXXXXXXXXXX-2541 HDFC Bank</p>
											</div>
										</div>
									</div>
									<div class="col-lg-6 col-md-6">
										<div class="invoice-total-card">
											<div class="invoice-total-box">
												<div class="invoice-total-inner">
													<p>Taxable <span>$6,660.00</span></p>
													<p>Additional Charges <span>$6,660.00</span></p>
													<p>Discount <span>$3,300.00</span></p>
													<p class="mb-0">Sub total <span>$3,300.00</span></p>
												</div>
												<div class="invoice-total-footer">
													<h4>Total Amount <span>$143,300.00</span></h4>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="invoice-sign-box">
									<div class="row">
										<div class="col-lg-8 col-md-8">
											<div class="invoice-terms">
												<h6>Notes:</h6>
												<p class="mb-0">Enter customer notes or any other details</p>
											</div>
											<div class="invoice-terms mb-0">
												<h6>Terms and Conditions:</h6>
												<p class="mb-0">Enter customer notes or any other details</p>
											</div>
										</div>
										<div class="col-lg-4 col-md-4">
											<div class="invoice-sign text-end">
												<img class="img-fluid d-inline-block" src="assets/img/signature.png" alt="sign">
												<span class="d-block">Harristemp</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Invoices Preview Modal -->

<!-- Add Invoices Modal -->
<div class="modal custom-modal fade bank-details" id="bank_details" role="dialog">
	<div class="modal-dialog modal-dialog-centered modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<div class="form-header text-start mb-0">
					<h4 class="mb-0">Add Bank Details</h4>
				</div>
				<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="bank-inner-details">
					<div class="row">
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<label>Account Holder Name</label>
								<input type="text" class="form-control" placeholder="Add Name">
							</div>
						</div>
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<label>Bank name</label>
								<input type="text" class="form-control" placeholder="Add Bank name">
							</div>
						</div>
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<label>IFSC Code</label>
								<input type="text" class="form-control">
							</div>
						</div>
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<label>Account Number</label>
								<input type="text" class="form-control">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="bank-details-btn">
					<a href="javascript:void(0);" data-bs-dismiss="modal" class="btn bank-cancel-btn me-2">Cancel</a>
					<a href="javascript:void(0);" class="btn bank-save-btn">Save Item</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Add Invoices Modal -->

<!-- Delete Invoices Modal -->
<div class="modal custom-modal fade" id="delete_invoices_details" role="dialog">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-body">
				<div class="form-header">
					<h3>Delete Invoice Details</h3>
					<p>Are you sure want to delete?</p>
				</div>
				<div class="modal-btn delete-action">
					<div class="row">
						<div class="col-6">
							<a href="javascript:void(0);" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Delete</a>
						</div>
						<div class="col-6">
							<a href="javascript:void(0);" data-bs-dismiss="modal" class="btn btn-primary paid-cancel-btn">Cancel</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Delete Invoices Modal -->

<!-- Save Invoices Modal -->
<div class="modal custom-modal fade" id="save_invocies_details" role="dialog">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-body">
				<div class="form-header">
					<h3>Save Invoice Details</h3>
					<p>Are you sure want to save?</p>
				</div>
				<div class="modal-btn delete-action">
					<div class="row">
						<div class="col-6">
							<a href="javascript:void(0);" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Save</a>
						</div>
						<div class="col-6">
							<a href="javascript:void(0);" data-bs-dismiss="modal" class="btn btn-primary paid-cancel-btn">Cancel</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Save Invoices Modal -->
