// reactjs-files/template-rtl/src/invoices/Banksettings.jsx
import React, {useState, useEffect} from 'react'
import { Link } from 'react-router-dom';
import Select2 from 'react-select2-wrapper';
import DatePicker from 'react-datepicker';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import {Logo,signature,circle1,circle2} from "../_components/imagepath"
import FeatherIcon from 'feather-icons-react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const Banksettings = () => {

	const [menu, setMenu] = useState(false)
	const [date, setDate] = useState(new Date());
	const toggleMobileMenu = () => {
		setMenu(!menu)
	  }
	  
	
	const [options, setOptions] = useState([
        { id: 1, text: 'Select Customer' },
        { id: 2, text: 'Brian Johnson' },
        { id: 3, text: 'Marie Canales' },
        { id: 4, text: 'Barbara Moore' },
        { id: 5, text: 'Greg Lynch' },
        { id: 6, text: 'Karlene Chaidez' }
	]);

    useEffect(() => {
        let elements = Array.from(document.getElementsByClassName('react-datepicker-wrapper'));
        elements.map(element => element.classNameList.add("width-100"))
	},[]);

    const handleChange = (date) => {
        setDate(date)
    }

	return (

		<>
	<div className={`main-wrapper ${menu ? 'slide-nav': ''}`}> 
          
          <Header onMenuClick={(defaultValue) => toggleMobileMenu()} />
          <Sidebar /> 
		  {/* <!-- Page Wrapper --> */}
			<div className="page-wrapper">
				<div className="content container-fluid">

					{/* <!-- Page Header --> */}
					<div className="page-header">
						<div className="row">
							<div className="col-sm-6">
								<h3 className="page-title">Invoice settings</h3>
								<ul className="breadcrumb">
									<li className="breadcrumb-item"><Link to="/index">Dashboard</Link>
									</li>
									<li className="breadcrumb-item active">Bank Settings</li>
								</ul>
							</div>
						</div>
					</div>
					{/* <!-- /Page Header --> */}
				
					<div className="row">
						<div className="col-xl-3 col-md-4">
							<div className="widget settings-menu">
								<ul>
									<li className="nav-item">
										<Link to="/invoices-settings" className="nav-link">
											<FeatherIcon icon="git-commit"/> <span>General Settings</span>
										</Link>
									</li>
									<li className="nav-item">
										<Link to="/tax-settings" className="nav-link">
											<FeatherIcon icon="bookmark"/> <span>Tax Settings</span>
										</Link>
									</li>
									<li className="nav-item">
										<Link to="/bank-settings" className="nav-link active">
											<i className="fas fa-university"></i> <span>Bank Settings</span>
										</Link>
									</li>
								</ul>
							</div>
						</div>
						
						<div className="col-xl-9 col-md-8">
							<div className="card invoices-settings-card">
								<div className="card-header">
									<h5 className="card-title">Bank Settings</h5>
								</div>
								<div className="card-body">
								
									{/* <!-- Form --> */}
									<form action="#" className="invoices-settings-form">
										<div className="row align-items-center form-group">
											<label htmlFor="name" className="col-sm-3 col-form-label input-label">Default Bank Account</label>
											<div className="col-sm-9">
												<label className="custom_check">
													<input type="checkbox" name="invoice"/>
													<span className="checkmark"></span> Check to enable Bank Account default
												</label>
											</div>
										</div>
										<div className="row align-items-center form-group">
											<label htmlFor="email" className="col-sm-3 col-form-label input-label">Account Holder Name</label>
											<div className="col-sm-9">
												<input type="text" className="form-control"/>
											</div>
										</div>
										<div className="row align-items-center form-group">
											<label htmlFor="phone" className="col-sm-3 col-form-label input-label">Bank name</label>
											<div className="col-sm-9">
												<input type="text" className="form-control"/>
											</div>
										</div>
										<div className="row align-items-center form-group">
											<label htmlFor="phone" className="col-sm-3 col-form-label input-label">IFSC Code</label>
											<div className="col-sm-9">
												<input type="text" className="form-control"/>
											</div>
										</div>
										<div className="row align-items-center form-group">
											<label htmlFor="phone" className="col-sm-3 col-form-label input-label">Account Number</label>
											<div className="col-sm-9">
												<input type="text" className="form-control"/>
											</div>
										</div>
										<div className="invoice-setting-btn text-end">
											<button type="submit" className="btn cancel-btn ms-2">Cancel</button>
											<button type="submit" className="btn btn-primary">Save Changes</button>
										</div>
									</form>
									{/* <!-- /Form --> */}
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{/* <!-- /Page Wrapper --> */}
			
		</div>	
			</>
        );
    }
export default Banksettings;

// angular-files/template/src/app/bank-settings/bank-settings.component.ts
import { Component, OnInit } from '@angular/core';
import * as Feather from 'feather-icons';

@Component({
  selector: 'app-bank-settings',
  templateUrl: './bank-settings.component.html',
  styleUrls: ['./bank-settings.component.css']
})
export class BankSettingsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  ngAfterViewInit() {
    this.loadfeather("assets/plugins/icons/feather/feather.css")
  }
  loadfeather(js) {
    var script = document.createElement('link');
    script.href = js;
    script.rel = "stylesheet"
    document.head.appendChild(script);
  }
}

<!-- Page Wrapper -->
<div class="page-wrapper">
    <div class="content container-fluid">

        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-6">
                    <h3 class="page-title">Invoice settings</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a [routerLink]="'/index'">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item active">Bank Settings</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
    
        <div class="row">
            <div class="col-xl-3 col-md-4">
                <div class="widget settings-menu">
                    <ul>
                        <li class="nav-item">
                            <a [routerLink]="'/invoices-settings'" class="nav-link">
                                <i class="fe fe-git-commit"></i> <span>General Settings</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a [routerLink]="'/tax-settings'" class="nav-link">
                                <i class="fe fe-bookmark"></i> <span>Tax Settings</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a [routerLink]="'/bank-settings'" class="nav-link active">
                                <i class="fas fa-university"></i> <span>Bank Settings</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            
            <div class="col-xl-9 col-md-8">
                <div class="card invoices-settings-card">
                    <div class="card-header">
                        <h5 class="card-title">Bank Settings</h5>
                    </div>
                    <div class="card-body">
                    
                        <!-- Form -->
                        <form action="#" class="invoices-settings-form">
                            <div class="row align-items-center form-group">
                                <label for="name" class="col-sm-3 col-form-label input-label">Default Bank Account</label>
                                <div class="col-sm-9">
                                    <label class="custom_check">
                                        <input type="checkbox" name="invoice">
                                        <span class="checkmark"></span> Check to enable Bank Account default
                                    </label>
                                </div>
                            </div>
                            <div class="row align-items-center form-group">
                                <label for="email" class="col-sm-3 col-form-label input-label">Account Holder Name</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="row align-items-center form-group">
                                <label for="phone" class="col-sm-3 col-form-label input-label">Bank name</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="row align-items-center form-group">
                                <label for="phone" class="col-sm-3 col-form-label input-label">IFSC Code</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="row align-items-center form-group">
                                <label for="phone" class="col-sm-3 col-form-label input-label">Account Number</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="invoice-setting-btn text-end">
                                <button type="submit" class="btn cancel-btn me-2">Cancel</button>
                                <button type="submit" class="btn btn-primary">Save Changes</button>
                            </div>
                        </form>
                        <!-- /Form -->
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Page Wrapper -->
