// reactjs-files/template/src/customers/AddCustomer.jsx
import React, {useEffect, useState} from 'react';
import { Link } from 'react-router-dom';
import Select2 from 'react-select2-wrapper';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'

const AddCustomer = () => {

    const [menu, setMenu] = useState(false)

	const toggleMobileMenu = () => {
		setMenu(!menu)
	  }

    const [date, setDate] = useState(new Date());
	const [currencyOptions, setcurrencyOptions] = useState( [
        { id: 1, text: 'Select Currency' },
        { id: 2, text: 'EUR Euro' },
        { id: 3, text: 'INR Indoan Rupee' },
        { id: 4, text: 'USD- US Dollar' }
    ]);
    const [countryOptions, setcountryOptions] = useState( [
        {  id: 1, text: 'Select Country' },
        {  id: 2, text: 'Afghanistan' },
        {  id: 3, text: 'Albania' },
        {  id: 4, text: 'American Samoa' },
        {  id: 5, text: 'Algeria' },
        {  id: 6, text: 'Andorra' },
        {  id: 7, text: 'Angola' },
        {  id: 8, text: 'Anguilla' },
        {  id: 9, text: 'United States' }
    ]);

        return (

            <>
            <div className={`main-wrapper ${menu ? 'slide-nav': ''}`}> 
          
          <Header onMenuClick={(value) => toggleMobileMenu()} />
          <Sidebar />
                <div className="page-wrapper">
                    <div className="content container-fluid">
                    
    
                        <div className="page-header">
                            <div className="row">
                                <div className="col-sm-12">
                                    <h3 className="page-title">Customers</h3>
                                    <ul className="breadcrumb">
                                        <li className="breadcrumb-item"><Link to="/index">Dashboard</Link></li>
                                        <li className="breadcrumb-item"><Link to="/customers">Customers</Link></li>
                                        <li className="breadcrumb-item active">Add Customers</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        
                        <div className="row">
                            <div className="col-md-12">
                                <div className="card">
                                    <div className="card-body">
                                        <h4 className="card-title">Basic Info</h4>
                                        <form action="#">
                                            <div className="row">
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Name</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Email</label>
                                                        <input type="email" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Primary Currency</label>
                                                        <Select2
                                                             className="w-100"
                                                            data={currencyOptions}
                                                            options={{
                                                                placeholder: 'Currency',
                                                            }}
                                                        />
                                                    </div>
                                                </div>
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Primary Contact Name</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Phone</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Website</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        <h4 className="card-title mt-4">Billing Address</h4>
                                        <form action="#">
                                            <div className="row">
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Name</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>State</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Address</label>
                                                        <textarea rows="5" cols="5" className="form-control" placeholder="Enter Address"></textarea>
                                                    </div>
                                                </div>
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Country</label>
                                                        <Select2
                                                            className="w-100"
                                                            data={countryOptions}
                                                            options={{
                                                                placeholder: 'Country',
                                                            }}
                                                        />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>City</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Phone</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Zip Code</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        <h4 className="card-title mt-4">Shipping Address</h4>
                                        <form action="#">
                                            <div className="text-end">
                                                <button type="submit" className="btn btn-outline-primary btn-sm">Copy from Billing</button>
                                            </div>
                                            <div className="row">
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Name:</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>State:</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Address:</label>
                                                        <textarea rows="5" cols="5" className="form-control" placeholder="Enter Address"></textarea>
                                                    </div>
                                                </div>
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Country:</label>
                                                        <Select2
                                                             className="w-100"
                                                            data={countryOptions}
                                                            options={{
                                                                placeholder: 'Country',
                                                            }}
                                                        />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>City:</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Phone:</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Zip Code:</label>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="text-end mt-4">
                                                <button type="submit" className="btn btn-primary">Add Customer</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                
           </>
        );
}
export default AddCustomer;

// angular-files/template/src/app/add-customer/add-customer.component.ts
import { Component, OnInit, TemplateRef } from '@angular/core';
import { CommonServiceService } from '../common-service.service';
import { Event, Router, NavigationStart, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { FormBuilder, FormGroup, Validators } from "@angular/forms";
import { AllModulesService } from '../all-modules.service';
import { DatePipe } from "@angular/common";
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-add-customer',
  templateUrl: './add-customer.component.html',
  styleUrls: ['./add-customer.component.css']
})
export class AddCustomerComponent implements OnInit {
  public id;
  public url: any = "customers";
  page = 'Add Customer';
  public pipe = new DatePipe("en-US");
  myDate = new Date();
  public addCustomerForm: FormGroup;
  constructor(public router: Router, location: Location, private allModulesService: AllModulesService,private formBuilder: FormBuilder,private route: ActivatedRoute,private toastr: ToastrService) { 
  }

  ngOnInit(): void {
    
    this.addCustomerForm = this.formBuilder.group({
      customerName: ["", [Validators.required]],
      customerEmail: ["", [Validators.required]],
      customerCurrency: ["", [Validators.required]],
      customerPrimaryContact: ["", [Validators.required]],
      customerPhone: ["", [Validators.required]],
      customerWebsite: ["", [Validators.required]],
      customerBillingName: ["", [Validators.required]],
      customerBillingState: ["", [Validators.required]],
      customerBillingAddress: ["", [Validators.required]],
      customerBillingCountry: ["", [Validators.required]],
      customerBillingCity: ["", [Validators.required]],
      customerBillingPhone: ["", [Validators.required]],
      customerBillingZip: ["", [Validators.required]],
      customerShippingName: ["", [Validators.required]],
      customerShippingState: ["", [Validators.required]],
      customerShippingAddress: ["", [Validators.required]],
      customerShippingCountry: ["", [Validators.required]],
      customerShippingCity: ["", [Validators.required]],
      customerShippingPhone: ["", [Validators.required]],
      customerShippingZip: ["", [Validators.required]],
    });
  }
  private markFormGroupTouched(formGroup: FormGroup) {
    (<any>Object).values(formGroup.controls).forEach((control) => {
      control.markAsTouched();
      if (control.controls) {
        this.markFormGroupTouched(control);
      }
    });
  }
  addCustomer() {
    if(this.addCustomerForm.invalid){
      this.markFormGroupTouched(this.addCustomerForm)
      return
    }
    else {
      
    let DateJoin = this.pipe.transform(
      this.myDate,"dd-MM-yyyy"
    );
    let obj = {
      name : this.addCustomerForm.value.customerName,
      email : this.addCustomerForm.value.customerEmail,
      phone : this.addCustomerForm.value.customerPrimaryContact,
      amount_due : "$8295",
      registered_on : DateJoin,            
      status : "Active",
      role: "Customer"
    };
    this.allModulesService.add(obj, this.url).subscribe((data) => {
      
    });
    this.router.navigate(["/customers"]);
    this.toastr.success("Customer added sucessfully...!", "Success");
    }
  }
  
}

<!-- Page Wrapper -->
			<div class="page-wrapper">
				<div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row">
							<div class="col-sm-12">
								<h3 class="page-title">Customers</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a [routerLink]="'/'">Dashboard</a></li>
									<li class="breadcrumb-item"><a [routerLink]="'/customers'">Customers</a></li>
									<li class="breadcrumb-item active">Add Customers</li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
					
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-body">
									<h4 class="card-title">Basic Info</h4>
									<form (ngSubmit)="addCustomer()" [formGroup]="addCustomerForm">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label>Name</label>
													<input type="text" class="form-control" formControlName="customerName">
													<div *ngIf="addCustomerForm.get('customerName').invalid && addCustomerForm.get('customerName').touched">
                            							<small class="text-danger">*Name required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Email</label>
													<input type="email" class="form-control" formControlName="customerEmail">
													<div *ngIf="addCustomerForm.get('customerEmail').invalid && addCustomerForm.get('customerEmail').touched">
                            							<small class="text-danger">*Email required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Primary Currency</label>
													<select class="form-select" formControlName="customerCurrency">
														<option>Select Currency</option>
														<option>EUR Euro</option>
														<option>INR Indoan Rupee</option>
														<option>USD- US Dollar</option>
													</select>
													<div *ngIf="addCustomerForm.get('customerCurrency').invalid && addCustomerForm.get('customerCurrency').touched">
                            							<small class="text-danger">*Currency is required</small>
													</div>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<label>Primary Contact Name</label>
													<input type="text" class="form-control" formControlName="customerPrimaryContact">
													<div *ngIf="addCustomerForm.get('customerPrimaryContact').invalid && addCustomerForm.get('customerPrimaryContact').touched">
                            							<small class="text-danger">*Primary Contact is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Phone</label>
													<input type="text" class="form-control" formControlName="customerPhone">
													<div *ngIf="addCustomerForm.get('customerPhone').invalid && addCustomerForm.get('customerPhone').touched">
                            							<small class="text-danger">*Phone Number is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Website</label>
													<input type="text" class="form-control" formControlName="customerWebsite">
													<div *ngIf="addCustomerForm.get('customerWebsite').invalid && addCustomerForm.get('customerWebsite').touched">
                            							<small class="text-danger">*Website is required</small>
													</div>
												</div>
											</div>
										</div>
										<h4 class="card-title mt-4">Billing Address</h4>
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label>Name</label>
													<input type="text" class="form-control" formControlName="customerBillingName">
													<div *ngIf="addCustomerForm.get('customerBillingName').invalid && addCustomerForm.get('customerBillingName').touched">
                            							<small class="text-danger">*Billing Name is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>State</label>
													<input type="text" class="form-control" formControlName="customerBillingState">
													<div *ngIf="addCustomerForm.get('customerBillingState').invalid && addCustomerForm.get('customerBillingState').touched">
                            							<small class="text-danger">*Billing State is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Address</label>
													<textarea rows="5" cols="5" class="form-control" placeholder="Enter Address" formControlName="customerBillingAddress"></textarea>
													<div *ngIf="addCustomerForm.get('customerBillingAddress').invalid && addCustomerForm.get('customerBillingAddress').touched">
                            							<small class="text-danger">*Billing Address is required</small>
													</div>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<label>Country</label>
													<select class="form-select" formControlName="customerBillingCountry">
														<option>Select Country</option>
														<option>Afghanistan</option>
														<option>Afghanistan</option>
														<option>Albania</option>
														<option>Algeria</option>
														<option>American Samoa</option>
														<option>Andorra</option>
														<option>Angola</option>
														<option>Anguilla</option>
														<option selected>United States</option>
													</select>
													<div *ngIf="addCustomerForm.get('customerBillingCountry').invalid && addCustomerForm.get('customerBillingCountry').touched">
                            							<small class="text-danger">*Billing Country is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>City</label>
													<input type="text" class="form-control" formControlName="customerBillingCity">
													<div *ngIf="addCustomerForm.get('customerBillingCity').invalid && addCustomerForm.get('customerBillingCity').touched">
                            							<small class="text-danger">*Billing City is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Phone</label>
													<input type="text" class="form-control" formControlName="customerBillingPhone">
													<div *ngIf="addCustomerForm.get('customerBillingPhone').invalid && addCustomerForm.get('customerBillingPhone').touched">
                            							<small class="text-danger">*Billing Phone Nomber is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Zip Code</label>
													<input type="text" class="form-control" formControlName="customerBillingZip">
													<div *ngIf="addCustomerForm.get('customerBillingZip').invalid && addCustomerForm.get('customerBillingZip').touched">
                            							<small class="text-danger">*Billing Zipcode is required</small>
													</div>
												</div>
											</div>
										</div>
										<h4 class="card-title mt-4">Shipping Address</h4>
										<div class="text-end">
											<button type="submit" class="btn btn-outline-primary btn-sm">Copy from Billing</button>
										</div>
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label>Name:</label>
													<input type="text" class="form-control" formControlName="customerShippingName">
													<div *ngIf="addCustomerForm.get('customerShippingName').invalid && addCustomerForm.get('customerShippingName').touched">
                            							<small class="text-danger">*Shipping Name is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>State:</label>
													<input type="text" class="form-control" formControlName="customerShippingState">
													<div *ngIf="addCustomerForm.get('customerShippingState').invalid && addCustomerForm.get('customerShippingState').touched">
                            							<small class="text-danger">*Shipping State is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Address:</label>
													<textarea rows="5" cols="5" class="form-control" placeholder="Enter Address" formControlName="customerShippingAddress"></textarea>
													<div *ngIf="addCustomerForm.get('customerShippingAddress').invalid && addCustomerForm.get('customerShippingAddress').touched">
                            							<small class="text-danger">*Shipping Address is required</small>
													</div>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<label>Country:</label>
													<select class="form-select" formControlName="customerShippingCountry">
														<option>Select Country</option>
														<option value="Afganistan">Afghanistan</option>
														<option value="Albania">Albania</option>
														<option value="Algeria">Algeria</option>
														<option value="American Samoa">American Samoa</option>
														<option value="Andorra">Andorra</option>
														<option value="Angola">Angola</option>
														<option value="Anguilla">Anguilla</option>
													</select>
													<div *ngIf="addCustomerForm.get('customerShippingCountry').invalid && addCustomerForm.get('customerShippingCountry').touched">
                            							<small class="text-danger">*Shipping Country is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>City:</label>
													<input type="text" class="form-control" formControlName="customerShippingCity">
													<div *ngIf="addCustomerForm.get('customerShippingCity').invalid && addCustomerForm.get('customerShippingCity').touched">
                            							<small class="text-danger">*Shipping City is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Phone:</label>
													<input type="text" class="form-control" formControlName="customerShippingPhone">
													<div *ngIf="addCustomerForm.get('customerShippingPhone').invalid && addCustomerForm.get('customerShippingPhone').touched">
                            							<small class="text-danger">*Shipping Phone is required</small>
													</div>
												</div>
												<div class="form-group">
													<label>Zip Code:</label>
													<input type="text" class="form-control" formControlName="customerShippingZip">
													<div *ngIf="addCustomerForm.get('customerShippingZip').invalid && addCustomerForm.get('customerShippingZip').touched">
                            							<small class="text-danger">*Shipping Zipcode is required</small>
													</div>
												</div>
											</div>
										</div>
										<div class="text-end mt-4">
											<button type="submit" class="btn btn-primary">Add Customer</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->
