// angular-files/template/src/app/salesreport/salesreport.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonServiceService } from '../common-service.service';
import * as $ from 'jquery';

@Component({
  selector: 'app-salesreport',
  templateUrl: './salesreport.component.html',
  styleUrls: ['./salesreport.component.css']
})
export class SalesreportComponent implements OnInit {

    expeses: any = [];
  errorMessage: string;
  constructor(public commonService: CommonServiceService) {}

  ngOnInit(): void {    
    this.getExpenses();
  }
  getExpenses() {
    this.commonService.getExpenses().subscribe((res) => {
      this.expeses = res;
     
    });
  }

}

<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Sales Report</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a [routerLink]="'/'">Dashboard</a></li>
									<li class="breadcrumb-item active">Reports</li>
								</ul>
							</div>
							<div class="col-auto">
								<a href="javascript:void(0);"  class="btn btn-primary me-1">
									<i class="fas fa-file-pdf"></i>
								</a>
								<a class="btn btn-primary filter-btn" href="javascript:void(0);" id="filter_search">
									<i class="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
			   
					<!-- Search Filter -->
					<div id="filter_inputs" class="card filter-card">
						<div class="card-body pb-0">
							<div class="row">
								<div class="col-md-4">
									<div class="form-group">
										<label>Slect Date Range</label>
										<ng-select2  width="100%">
											<option>Select</option>
											<option>Today</option>
											<option>This Week</option>
											<option>This Month</option>
											<option>This Quarter</option>
											<option>This Year</option>
											<option>Previous Week</option>
											<option>Previous Month</option>
											<option>Previous Quarter</option>
											<option>Previous Year</option>
										</ng-select2>
									</div>
								</div>
								
								<div class="col-md-4">
									<div class="form-group">
										<label>From</label>
										<div class="cal-icon">
											<input type="text" class="form-control" name="dp"  (click)="d1.toggle()" ngbDatepicker #d1="ngbDatepicker">
										</div>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>To</label>
										<div class="cal-icon">
											<input type="text" class="form-control" name="dp"  (click)="d.toggle()" ngbDatepicker #d="ngbDatepicker">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /Search Filter -->
					
					<div class="row">
						<div class="col-sm-12">
							<div class="card card-table"> 
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-center table-hover datatable">
											<thead class="thead-light">
												<tr>
													<th>#</th>
													<th>Date</th>
													<th>Category</th>
													<th>Sales</th>
													<th>Refunded</th>
													<th>Discounts</th>
													<th>Taxs</th>
													<th>Amount</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>1</td>
													<td>7 Jan 2021</td>
													<td>Accessories</td>
													<td>$42</td>
													<td>$0</td>
													<td>$163</td>
													<td>$221</td>
													<td>$762</td>
												</tr>
												<tr>
													<td>2</td>
													<td>28 Feb 2021</td>
													<td>Books</td>
													<td>$1249</td>
													<td>$36</td>
													<td>$3</td>
													<td>$80</td>
													<td>$1238</td>
												</tr>
												<tr>
													<td>3</td>
													<td>10 Mar 2021</td>
													<td>Others</td>
													<td>$76</td>
													<td>$0</td>
													<td>$0</td>
													<td>$4</td>
													<td>$80</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
					
				</div>			
			</div>
			<!-- /Page Wrapper -->

// reactjs-files/template/src/reports/salesreport.jsx
import React, {useEffect, useState} from 'react';
import { Link } from 'react-router-dom';
import Select2 from 'react-select2-wrapper';
import { Row, Col, Card, Media } from "react-bootstrap";
import DataTable from 'react-data-table-component';
import DataTableExtensions from 'react-data-table-component-extensions';
import 'react-data-table-component-extensions/dist/index.css';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'

const SlideToggle = window.ReactSlideToggle

const SalesReport = () => {

	const [menu, setMenu] = useState(false)

	const toggleMobileMenu = () => {
		setMenu(!menu)
	  }
	const [date_range_, setdaterange] = useState( [
            { id:2, text: 'Today' },
            { id:3, text: 'This Week' },
            { id:4, text: 'This Month' },
			{ id:5, text: 'This Quarter'},
            { id:6, text: 'This Year' },
            { id:7, text: 'Previous Week' },
            { id:8, text: 'Previous Month' },
			{ id:9, text: 'Previous Quarter'},
			{ id:10, text: 'Previous Year'}
		]);

		const data = [
			{
				"id": 1,
				"Date" : "7 Jan 2021",
				"Category": "Accessories",
				"Sales": "$42",
				"Refunded": "$0",
				"Discounts": "$163",
				"Taxs": "$221",
				"Amount": "$762",							
			},
			{
				"id": 2,
				"Date" : "28 Feb 2021",
				"Category": "Books",
				"Sales": "$1249",
				"Refunded": "$36",
				"Discounts": "$3",
				"Taxs": "$80",
				"Amount": "$1238",
			},
			{
				"id": 3,
				"Date" : "10 Mar 2021",
				"Category": "Others",
				"Sales": "$76",
				"Refunded": "$0",
				"Discounts": "$0",
				"Taxs": "$4",
				"Amount": "$80",
			},
		]

		const columns = [	
	 
			{
				name: '#',
				selector: row=>row.id,
				sortable: true,	
				width:"250px",							
			},
			{
				name: 'Date',
				selector: row=>row.Date,
				sortable: true,	
				width:"250px",							
			},			
			{
				name: 'Category',
				selector: row=>row.Category,
				sortable: true,	
				width:"250px",							
			},																																			
			{
				name: 'Sales',
				selector: row=>row.Sales,			
				sortable: true,	
				width:"250px",			
			},	
			{
				name: 'Refunded',
				selector: row=>row.Refunded,
				sortable: true,	
				width:"250px",			
			},
			{
				name: 'Discounts',
				selector: row=>row.Discounts,
				sortable: true,
				width:"250px",
			},			
			{
				name: 'Taxs',
				selector: row=>row.Taxs,
				sortable: true,	
				width:"250px",			
			},
			{
				name: 'Amount',
				selector: row=>row.Amount,
				sortable: true,
				width:"250px",
			},	
			
		];
		
		const tableData = {
			columns,
			data,
		};
		
	
    return (
	
		<div className={`main-wrapper ${menu ? 'slide-nav': ''}`}> 
          
			<Header onMenuClick={(value) => toggleMobileMenu()} />
			<Sidebar /> 
			<div className="page-wrapper">
				<div className="content container-fluid">
				
					<div className="page-header">
						<div className="row align-items-center">
							<div className="col">
								<h3 className="page-title">Sales Report</h3>
								<ul className="breadcrumb">
									<li className="breadcrumb-item"><Link to="/index">Dashboard</Link>
									</li>
									<li className="breadcrumb-item active">Reports</li>
								</ul>
							</div>
							<div className="col-auto">
								<a href="#" className="btn btn-primary me-1">
								<i className="fas fa-file-pdf" />
								</a>
								<a
								className="btn btn-primary filter-btn"
								href="/expenses-report#"
								id="filter_search"
								>
								<i className="fas fa-filter" />
								</a>
							</div>
						</div>
					</div>
                    {/* Search Filter */}
                    <div id="filter_inputs" className="card filter-card">
                        <div className="card-body pb-0">
                        <div className="row">
                            <div className="col-md-3">
                            <div className="form-group">
                                <label>Slect Date Range</label><br/>
                                <Select2 style={{ innerWidth : "250px" }}
                                    className="w-100"
                                    data={date_range_}
                                    options={{
                                        placeholder: 'Select',
                                    }}
                                />                                
                            </div>
                            </div>
                            <div className="col-md-3">
                            <div className="form-group">
                                <label>From</label>
                                <div className="">
                                <input className="form-control datetimepicker" type="date" />
                                </div>
                            </div>
                            </div>
                            <div className="col-md-3">
                            <div className="form-group">
                                <label>To</label>
                                <div className="">
                                <input className="form-control datetimepicker" type="date" />
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    {/* /Search Filter */}
					
					<div className="row">
						<div className="col-sm-12">
							<div className="card card-table">
								<div className="card-body">
									<div className="table-responsive">
										
											
											<DataTableExtensions
												{...tableData}
											>
												<DataTable
													noHeader
													defaultSortField="id"
													defaultSortAsc={false}
													pagination
													highlightOnHover
												/>
											</DataTableExtensions>
										
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>	

        );
}
export default SalesReport;
