// vuejs-files/template-rtl/src/views/uiinterface/components/Dropdown.vue
<template>
<!-- Dropdowns -->
						<section class="comp-section comp-dropdowns">
							<div class="section-header">
                                <h3 class="section-title">Dropdowns</h3>
                                <div class="line"></div>
                            </div>
							<div class="card bg-white">
								<div class="card-body">
									<h5 class="card-title">Dropdowns within Text</h5>
									<div class="dropdown">
										<a class="dropdown-toggle" href="javascript:void(0)" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Dropdown </a>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
										</div>
									</div>
									<hr>
									<h5 class="card-title">Dropdowns within Buttons</h5>
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-info dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<hr>
									<h5 class="card-title">Split button dropdowns</h5>
									<div class="btn-group">
										<button type="button" class="btn btn-primary">Action</button>
										<button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-secondary">Action</button>
										<button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-info">Action</button>
										<button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-success">Action</button>
										<button type="button" class="btn btn-success dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-warning">Action</button>
										<button type="button" class="btn btn-warning dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
									<div class="btn-group ms-1">
										<button type="button" class="btn btn-danger">Action</button>
										<button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="javascript:void(0)">Action</a>
											<a class="dropdown-item" href="javascript:void(0)">Another action</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0)">Separated link</a>
										</div>
									</div>
								</div>
							</div>
						</section>
						<!-- /Dropdowns -->
</template>

// reactjs-files/template-rtl/src/_components/dropdown/Dropdown.jsx
import React from 'react';

const Dropdown = () => {
  
  return ( 

     <>   
      {/* Dropdowns */}
      <section className="comp-section comp-dropdowns">
        <div className="section-header">
            <h3 className="section-title">Dropdowns</h3>
            <div className="line" />
        </div>
        <div className="card bg-white">
            <div className="card-body">
            <h5 className="card-title">Dropdowns within Text</h5>
            <div className="dropdown">
                <a
                className="dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                >
                {" "}
                Dropdown{" "}
                </a>
                <div className="dropdown-menu">
                <a className="dropdown-item" href="#">
                    Action
                </a>
                <a className="dropdown-item" href="#">
                    Another action
                </a>
                </div>
            </div>
            <hr />
            <h5 className="card-title">Dropdowns within Buttons</h5>
            <div className="btn-group">
            <button type="button" className="btn btn-primary dropdown-toggle me-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-secondary dropdown-toggle me-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-info dropdown-toggle me-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-success dropdown-toggle me-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-warning dropdown-toggle me-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-danger dropdown-toggle me-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <hr />
            <h5 className="card-title">Split button dropdowns</h5>
            <div className="btn-group">
            <button type="button" className="btn btn-primary me-1">Action</button>
            <button type="button" className="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span className="sr-only">Toggle Dropdown</span>
            </button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-secondary me-1">Action</button>
            <button type="button" className="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span className="sr-only">Toggle Dropdown</span>
            </button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-info me-1">Action</button>
            <button type="button" className="btn btn-info dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span className="sr-only">Toggle Dropdown</span>
            </button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-success me-1">Action</button>
            <button type="button" className="btn btn-success dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span className="sr-only">Toggle Dropdown</span>
            </button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-warning me-1">Action</button>
            <button type="button" className="btn btn-warning dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span className="sr-only">Toggle Dropdown</span>
            </button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
            <div className="btn-group">
            <button type="button" className="btn btn-danger me-1">Action</button>
            <button type="button" className="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span className="sr-only">Toggle Dropdown</span>
            </button>
            <div className="dropdown-menu">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <div className="dropdown-divider" />
                <a className="dropdown-item" href="#">Separated link</a>
            </div>
            </div>
        </div>
    </div>
    </section>
    {/* /Dropdowns */}
   </>
  )
}

export default Dropdown
