// reactjs-files/template-rtl/src/estimates/Index.jsx
import React, {useState, useEffect} from 'react'
import { Link } from 'react-router-dom'
import { Row, Col, Card, Media } from "react-bootstrap";
import Select2 from 'react-select2-wrapper';
import DatePicker from 'react-datepicker';
import DataTable from 'react-data-table-component';
import DataTableExtensions from 'react-data-table-component-extensions';
import 'react-data-table-component-extensions/dist/index.css';
import {img12,img5,img2,img3,img4,img11,img7,img6,img8,img9 } from "../_components/imagepath"
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'

const Estimates = () => {

	const [menu, setMenu] = useState(false)

	const toggleMobileMenu = () => {
		setMenu(!menu)
	  }

    const [date, setDate] = useState(new Date());
	const [options, setOptions] = useState([
		{ id: 1, text: 'Draft' },
		{ id: 2, text: 'Sent' },
		{ id: 3, text: 'Viewed' },
		{ id: 4, text: 'Expired' },
		{ id: 5, text: 'Accepted' },
		{ id: 6, text: 'Rejected' },
	]);
	const data = [
        {
            "EstimateNumber": "EST-17ER281",
            "Customer": " Marie Canales",
            "img_url": img3,
            "EstimateDate": "16 Nov 2020",
            "ExpiryDate": "22 Nov 2020",
            "Amount": "$100",
            "status": "Accepted"
        },
        {
            "EstimateNumber": "EST-26AS699",
            "Customer": "Barbara Moore",
            "img_url": img4,
            "EstimateDate": "5 Nov 2020",
            "ExpiryDate": "10 Nov 2020",
            "Amount": "$75",
            "status": "Declined"
        },
        {
            "EstimateNumber": "EST-11KI214",
            "Customer": "Greg Lynch",
            "img_url": img5,
            "EstimateDate": "1 Nov 2020",
            "ExpiryDate": "5 Nov 2020",
            "Amount": "$175",
            "status": "Sent"
        },
        {
            "EstimateNumber": "EST-98HJ687",
            "Customer": "Karlene Chaidez",
            "img_url": img6,
            "EstimateDate": "24 Oct 2020",
            "ExpiryDate": "28 Oct 2020",
            "Amount": "$1500",
            "status": "Expired"
        },
        {
            "EstimateNumber": "EST-71DR001",
            "Customer": " John Blair",
            "img_url": img7,
            "EstimateDate": "12 Oct 2020",
            "ExpiryDate": "17 Oct 2020",
            "Amount": "$2350",
            "status": "Accepted"
        },
        {
            "EstimateNumber": "EST-68MN425",
            "Customer": "Russell Copeland",
            "img_url": img8,
            "EstimateDate": "2 Oct 2020",
            "ExpiryDate": "8 Oct 2020",
            "Amount": "$1890",
            "status": "Accepted"
        },
        {
            "EstimateNumber": "EST-86YU963",
            "Customer": " Leatha Bailey",
            "img_url": img9,
            "EstimateDate": "25 Sep 2020",
            "ExpiryDate": "30 Sep 2020",
            "Amount": "$785",
            "status": "Accepted"
        }
    ]
	const columns = [
	
			{
				name: 'EmailEstimate Number',
				selector: row=>row.EstimateNumber,
				sortable: true,
				cell: () => <a href="/view-estimate">EST-17ER281</a>,
				width:"250px",						
			},									
																										
		{
			name: 'Customer',			
			sortable: true,
			cell: row => <Media className="user-dt"><a href="/profile" className="avatar avatar-sm"><img src={row.img_url} className="avatar-img rounded-circle" /></a><Media.Body className="me-2">{row.Customer}</Media.Body></Media>,
			width:"250px",
		},
		{
			name: 'Estimate Date',
			selector: row=>row.EstimateDate,
			sortable: true,	
			width:"250px",			
		},
		{
			name: 'Expiry Date',
			selector: row=>row.ExpiryDate,
			sortable: true,
			width:"250px",
		},
		{
			name: 'Amount',
			selector: row=>row.Amount,
			sortable: true,
			width:"250px",
		},
		{
			name: 'Status',
			selector: row=>row.status,
			sortable: true,	
			cell: row => <Media className="user-dt"><span className={`badge badge-pill badge ${ row.status == "Accepted" ? 'bg-success-light' : row.status == "Expired" ? 'bg-warning-light' : row.status == "Sent" ? 'bg-info-light':'bg-danger-light' }`} >{row.status}</span><Media.Body></Media.Body></Media>,
			width:"250px",		
		},
		{
			name: 'Action',
			selector: row=>row.action,
			sortable: true,
			cell: () => 	
			<div className="dropdown dropdown-action">
				
			<a href="#" className="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i className="fas fa-ellipsis-h"></i></a>
			<div className="dropdown-menu dropdown-menu-right">
				<a className="dropdown-item" href="#"><i className="far fa-edit ms-2"></i>Edit</a>
				<a className="dropdown-item" href="#"><i className="far fa-trash-alt ms-2"></i>Delete</a>
				<a className="dropdown-item" href="/view-estimate"><i className="far fa-eye ms-2"></i>View</a>
				<a className="dropdown-item" href="#"><i className="far fa-file-alt ms-2"></i>Convert to Invoice</a>
				<a className="dropdown-item" href="#"><i className="far fa-check-circle ms-2"></i>Mark as sent</a>
				<a className="dropdown-item" href="#"><i className="far fa-paper-plane ms-2"></i>Send Estimate</a>
				<a className="dropdown-item" href="#"><i className="far fa-check-circle ms-2"></i>Mark as Accepted</a>
				<a className="dropdown-item" href="#"><i className="far fa-times-circle ms-2"></i>Mark as Rejected</a>
			</div>
		</div>,
		width:"250px",				 
		},
		
	];
	
	const tableData = {
		columns,
		data,
	};
	

    const handleChange = (date) => {
        setDate(date)
    }
    
        return (
		
			<>
			<div className={`main-wrapper ${menu ? 'slide-nav': ''}`}> 
          
          <Header onMenuClick={(value) => toggleMobileMenu()} />
          <Sidebar /> 
			<div className="page-wrapper">
				<div className="content container-fluid">
					<div className="page-header">
						<div className="row align-items-center">
							<div className="col">
								<h3 className="page-title">Estimates</h3>
								<ul className="breadcrumb">
									<li className="breadcrumb-item"><Link to="/index">Dashboard</Link>
									</li>
									<li className="breadcrumb-item active">Estimates</li>
								</ul>
							</div>
							<div className="col-auto">
								<Link to="/add-estimate" className="btn btn-primary ms-1">
									<i className="fas fa-plus"></i>
								</Link>
								<a className="btn btn-primary filter-btn" href="/estimates#" id="filter_search">
									<i className="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					
					<div id="filter_inputs" className="card filter-card">
						<div className="card-body pb-0">
							<div className="row">
								<div className="col-md-3">
									<div className="form-group">
										<label>Customer:</label>
										<input type="text" className="form-control" />
									</div>
								</div>
								<div className="col-md-2">
									<div className="form-group">
										<label>Status:</label>
                                        <Select2
                                            className="w-100"
                                            data={options}
                                            options={{
                                                placeholder: 'Select Status',
                                            }}
                                        />
									</div>
								</div>
								<div className="col-md-2">
									<div className="form-group">
										<label>From</label>
										<div className="cal-icon">
                                            <DatePicker
                                                selected={date}
                                                onChange={handleChange}
                                                className="form-control datetimepicker"
                                            />
										</div>
									</div>
								</div>
								<div className="col-md-2">
									<div className="form-group">
										<label>To</label>
										<div className="cal-icon">
                                            <DatePicker
                                                selected={date}
                                                onChange={handleChange}
                                                className="form-control datetimepicker"
                                            />
										</div>
									</div>
								</div>
								<div className="col-md-3">
									<div className="form-group">
										<label>Estimate Number</label>
										<input type="text" className="form-control" />
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div className="row">
						<div className="col-sm-12">
							<div className="card card-table"> 
								<div className="card-body">
								<div className="table-responsive">
																														
											<DataTableExtensions
												{...tableData}
											>
												<DataTable
													noHeader
													defaultSortField="id"
													defaultSortAsc={false}
													pagination
													highlightOnHover
												/>
											</DataTableExtensions>
																																													
							   		</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
			</>
        );
}
export default Estimates;

// angular-files/template-rtl/src/app/estimates/estimates.component.ts
import { Component, OnInit } from '@angular/core';
import { AllModulesService } from '../all-modules.service';

@Component({
  selector: 'app-estimates',
  templateUrl: './estimates.component.html',
  styleUrls: ['./estimates.component.css'],
})
export class EstimatesComponent implements OnInit {
  estimates: any = [];
  errorMessage: string;
  url: any = "estimates";
  public tempId: any;
  constructor(private srvModuleService: AllModulesService) {}

  ngOnInit(): void {
    this.getEstimates();
  }

  getEstimates() {
    this.srvModuleService.get(this.url).subscribe((res) => {
      this.estimates = res;
    },
  );
  }
  deleteEstimates() {
    this.srvModuleService.delete(this.tempId, this.url).subscribe((data) => {
        this.getEstimates();
    });
  }
}

<!-- Page Wrapper -->
<div class="page-wrapper">
	<div class="content container-fluid">
		<div class="page-header">
			<div class="row align-items-center">
				<div class="col">
					<h3 class="page-title">Estimates</h3>
					<ul class="breadcrumb">
						<li class="breadcrumb-item"><a [routerLink]="'/'">Dashboard</a>
						</li>
						<li class="breadcrumb-item active">Estimates</li>
					</ul>
				</div>
				<div class="col-auto">
					<a [routerLink]="'/add-estimate'" class="btn btn-primary me-2">
						<i class="fas fa-plus"></i>
					</a>
					<a class="btn btn-primary filter-btn" href="javascript:void(0);" id="filter_search">
						<i class="fas fa-filter"></i>
					</a>
				</div>
			</div>
		</div>	
		<!-- Search Filter -->
		<div id="filter_inputs" class="card filter-card">
			<div class="card-body pb-0">
				<div class="row">
					<div class="col-md-3">
						<div class="form-group">
							<label>Customer:</label>
							<input type="text" class="form-control">
						</div>
					</div>
					<div class="col-md-2">
						<div class="form-group">
							<label>Status:</label>
							<ng-select2  width="100%">
								<option>Select Status</option>
								<option value="Draft">Draft</option>
								<option value="Sent">Sent</option>
								<option value="Viewed">Viewed</option>
								<option value="Expired">Expired</option>
								<option value="Accepted">Accepted</option>
								<option value="Rejected">Rejected</option>
							</ng-select2>
						</div>
					</div>
					<div class="col-md-2">
						<div class="form-group">
							<label>From</label>
							<div class="cal-icon">
								<input type="text" class="form-control" name="dp"  (click)="d1.toggle()" ngbDatepicker #d1="ngbDatepicker">
							</div>
						</div>
					</div>
					<div class="col-md-2">
						<div class="form-group">
							<label>To</label>
							<div class="cal-icon">
								<input type="text" class="form-control" name="dp"  (click)="d.toggle()" ngbDatepicker #d="ngbDatepicker">
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="form-group">
							<label>Estimate Number</label>
							<input type="text" class="form-control">
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /Search Filter -->
		
		<div class="row">
			<div class="col-sm-12">
				<div class="card card-table"> 
					<div class="card-body">						
						<div class="table-responsive">
							<table class="table table-stripped table-hover datatable">
								<thead class="thead-light">
									<tr>
										<th>Estimate Number</th>
										<th>Customer</th>
										<th>Estimate Date</th>
										<th>Expiry Date</th>
										<th>Amount</th>
										<th>Status</th>
										<th class="text-end">Action</th>
									</tr>
								</thead>
								<tbody>
									<tr *ngFor="let estimate of estimates;let i = index">
										<td><a [routerLink]="'/view-estimate'">{{estimate.number}}</a></td>
										<td>
											<h2 class="table-avatar">
												<a [routerLink]="'/profile'"><img class="avatar avatar-sm me-2 avatar-img rounded-circle" src="assets/img/profiles/avatar-{{ i + 1 }}.jpg" alt="User Image">{{estimate.customer_name}}</a>
											</h2>
										</td>
										<td>{{estimate.estimate_date | date : 'dd MMM yyyy' }}</td>
										<td>{{estimate.expiry_date | date : 'dd MMM yyyy' }}</td>
										<td>{{estimate.amount}}</td>
										<td>
											<span *ngIf="estimate.status === 'Accepted'" class="badge bg-success-light">{{estimate.status}}</span>
											<span *ngIf="estimate.status === 'Declined'" class="badge bg-danger-light">{{estimate.status}}</span>
											<span *ngIf="estimate.status === 'Sent'" class="badge bg-info-light">{{estimate.status}}</span>
											<span *ngIf="estimate.status === 'Expired'" class="badge bg-warning-light">{{estimate.status}}</span>
										</td>
										<td class="text-end">
										<div class="dropdown dropdown-action">
											<a href="javascript:void(0)" class="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-h"></i></a>
											<div class="dropdown-menu dropdown-menu-right">
												<a class="dropdown-item" routerLink="/edit-estimate/" [queryParams]="{id: estimate.id}"><i class="far fa-edit me-2"></i>Edit</a>
												<a (click)="tempId = estimate.id" data-bs-toggle="modal" data-bs-target="#delete_estimate" class="dropdown-item" href="javascript:void(0);"><i class="far fa-trash-alt me-2"></i>Delete</a>
												<a class="dropdown-item" [routerLink]="'/view-estimate'"><i class="far fa-eye me-2"></i>View</a>
												<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-file-alt me-2"></i>Convert to Invoice</a>
												<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-check-circle me-2"></i>Mark as sent</a>
												<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-paper-plane me-2"></i>Send Estimate</a>
												<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-check-circle me-2"></i>Mark as Accepted</a>
												<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-times-circle me-2"></i>Mark as Rejected</a>
											</div>
										</div>
									</td>
									</tr>
								</tbody>
							</table>
						</div>
				   
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Page Wrapper -->
<!-- Delete Tax Modal -->
<div class="modal custom-modal fade" id="delete_estimate" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-icon text-center mb-3">
                    <i class="fas fa-trash-alt text-danger"></i>
                </div>
                <div class="modal-text text-center">
                    <h2>Delete Estimate</h2>
                    <p>Are you sure want to delete?</p>
                </div>
            </div>
            <div class="modal-footer text-center">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" (click)="deleteEstimates()" data-bs-dismiss="modal">Delete</button>
            </div>
        </div>
    </div>
</div>
<!-- /Delete Tax Modal -->
